### ISSUE TITLE
gulp dev won't work after YO update

### ISSUE THREAD

**Issue by oliwerhelsen** [electrode-io/electrode#103]
Always worked before. But now when i choose Hapi.js as my server it don't create plugins/webapp and it creates koa-server.js and express-server.js.

Any suggestions?

This is what i get in my terminal: 
[16:01:17] Using gulpfile ~/Projects/Private/ioliwer/ioliwer-se/gulpfile.js
[16:01:17] Starting 'dev'...
[16:01:17] Starting '.webpack-dev'...
[16:01:17] Finished '.webpack-dev' after 118 μs
[16:01:17] Starting 'server-dev'...
[16:01:17] Starting 'server-watch-$deps$'...
[16:01:17] Starting '.init-bundle.valid.log'...
[16:01:17] Finished '.init-bundle.valid.log' after 393 μs
[16:01:17] Finished 'server-watch-$deps$' after 2.06 ms
[16:01:17] Starting 'server-watch'...
[16:01:17] Starting 'generate-service-worker'...
[16:01:17] Finished 'generate-service-worker' after 362 μs
[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/ioliwer/Projects/Private/ioliwer/ioliwer-se/server/**/* /Users/ioliwer/Projects/Private/ioliwer/ioliwer-se/config/**/*
Entry point configuration is not found, using default entry point...
  0% compileevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:2992
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)
[16:01:19] 'server-dev' errored after 1.44 s
[16:01:19] Error: command exit code 1
    at error (/Users/ioliwer/Projects/Private/ioliwer/ioliwer-se/node_modules/electrode-gulp-helper/lib/exec.js:6:15)
    at shell.exec (/Users/ioliwer/Projects/Private/ioliwer/ioliwer-se/node_modules/electrode-gulp-helper/lib/exec.js:19:29)
    at /Users/ioliwer/Projects/Private/ioliwer/ioliwer-se/node_modules/shelljs/src/exec.js:180:7
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
[16:01:19] 'dev' errored after 1.44 s
[16:01:19] Error in plugin 'run-sequence(server-dev)'
Message:
    command exit code 1
Details:
    stdout: Entry point configuration is not found, using default entry point...

  0% compileevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:2992
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1257:14)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

Stack:
Error: command exit code 1
    at error (/Users/ioliwer/Projects/Private/ioliwer/ioliwer-se/node_modules/electrode-gulp-helper/lib/exec.js:6:15)
    at shell.exec (/Users/ioliwer/Projects/Private/ioliwer/ioliwer-se/node_modules/electrode-gulp-helper/lib/exec.js:19:29)
    at /Users/ioliwer/Projects/Private/ioliwer/ioliwer-se/node_modules/shelljs/src/exec.js:180:7
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)

**Comment by animesh10** [comment]
Hi @oliwerhelsen, the project now supports koa and express as well, so the files are to be expected. The plugins have been moved to the electrode-react-webapp node module. 
What version of yeoman did you upgrade to ? I am unable to reproduce your issue.
It will help if you share your node, yo and gulp versions.

**Comment by oliwerhelsen** [comment]
Hi @animesh10,
It was this onetime thing. Now everything works for me two. I comeback to you if i have it again.
