### ISSUE TITLE
Unable to run Clap DEV for Development mode app and got browser console log error for PROD mode

### ISSUE THREAD

**Issue by hari-007** [electrode-io/electrode#1104]
## Type of issue : Bug

* #### Unable to run DEV mode of electrode 'Hello World' app. 
* #### Cli error & Browser console error for both Dev & Prod Mode

----

## My environment

* *OS version/details*: `Mac 10.13.6`
* *Node version:* `10.14.2`
* *npm version:* `6.4.1`
* *Version of yo :* `2.0.5`

## Expected behavior

As mentioned in [Getting Started](https://www.electrode.io/docs/what_is_electrode.html) page of  electrode.io. It should start a electrode Hello from Electrode page.
* Dev mode should work with out build as like given in above link of two commands [ cd app**    && clap dev]
* Dev mode is not expected to throw any errors in console and cli
* Prod mode should never ever display errors in console.
* Prod & Dev UI should be same.

## Current behavior
* #### ![#f03c15](https://placehold.it/15/f03c15/000000?text=+) `"clap dev" is not working`.
* #### Initially dev mode didn't even work as expected, Showing same cli error on browser.But, After trail with ``` clap build ``` for prod, Now working on browser as like below image.
* #### npm run prod is working fine as a UI. But pouring browser console log errors.
* #### Dev & Prod UI is not same. Styles are not applying on Dev mode.

## Command line output

```
[nodemon] 1.18.9
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Users/jujha001/Documents/own/tests/electrode-app/config/**/*
[nodemon] starting `node /Users/jujha001/Documents/own/tests/electrode-app/node_modules/electrode-archetype-react-app/support/babel-run src/server`
info: APP_SRC_DIR set to src/
setup dev middleware failed { Error: Cannot find module 'electrode-archetype-react-app-dev/lib/webpack-dev-express'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Function.Module._load (/Users/jujha001/Documents/own/tests/electrode-app/node_modules/isomorphic-loader/lib/extend-require.js:89:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at require (/Users/jujha001/Documents/own/tests/electrode-app/src/server/express-server.js:15:22)
    at PassThroughHandlerContext.finallyHandler (/Users/jujha001/Documents/own/tests/electrode-app/node_modules/bluebird/js/release/finally.js:57:23)
    at PassThroughHandlerContext.tryCatcher (/Users/jujha001/Documents/own/tests/electrode-app/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jujha001/Documents/own/tests/electrode-app/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/jujha001/Documents/own/tests/electrode-app/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/Users/jujha001/Documents/own/tests/electrode-app/node_modules/bluebird/js/release/promise.js:606:10)
    at _drainQueueStep (/Users/jujha001/Documents/own/tests/electrode-app/node_modules/bluebird/js/release/async.js:142:12)
    at _drainQueue (/Users/jujha001/Documents/own/tests/electrode-app/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/Users/jujha001/Documents/own/tests/electrode-app/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jujha001/Documents/own/tests/electrode-app/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18) code: 'MODULE_NOT_FOUND' }

App listening on port: 3000
```
### Prod issue:
<img width="969" alt="screen shot 2018-12-23 at 5 18 04 pm" src="https://user-images.githubusercontent.com/5758223/50387985-6d1f1680-06d7-11e9-8e48-2be948a41b3d.png">

##### Before ```` npm run build ````  ( IDK, whether we need to run build for "dev mode" or nor)
<img width="968" alt="screen shot 2018-12-23 at 5 13 01 pm" src="https://user-images.githubusercontent.com/5758223/50387994-c2f3be80-06d7-11e9-9312-31edc6ba3b7a.png">

##### After ```` npm run build ````
<img width="964" alt="screen shot 2018-12-23 at 5 20 59 pm" src="https://user-images.githubusercontent.com/5758223/50387984-67c1cc00-06d7-11e9-9a9a-97e625f08943.png">

<img width="1146" alt="screen shot 2018-12-23 at 5 19 17 pm" src="https://user-images.githubusercontent.com/5758223/50387986-74462480-06d7-11e9-8011-2294dbc721a5.png">

**Comment by atlas1119** [comment]
I have same problem.

**Comment by jchip** [comment]
We are working on fixing this for express.
