### ISSUE TITLE
Upgrade to archetype-react ^6.4.0 breaks build

### ISSUE THREAD

**Issue by swashcap** [electrode-io/electrode#1168]
## Type of issue

Bug: the web application build breaks after upgrading the archetypes to `^6.4.0`.

## My environment

* *OS version/details*: `macOS 10.14.3`
* *Node version:* `10.15.1`
* *npm version:* `6.7.0`
* *Version of yo :* `n/a`

## Expected behavior

Upgrading to `electrode-archetype-react-app@^6.4.0` and `electrode-archetype-react-app-dev@^6.4.0` shouldn't cause breaks in the build process: the [changelog](https://github.com/electrode-io/electrode/blob/master/CHANGELOG.md#commits-28) doesn't call out anything required to upgrade to archetype-react v6.

## Current behavior

Running `clap dev` breaks the build with the error `'Error: Cannot find module \'electrode-archetype-opt-pwa\''`.

## Steps to reproduce the behavior

We have an internal application, making this difficult to reproduce 😕

## Command line output

```shell
$ npx clap dev
[10:04:12] xclap version 0.2.28 at CWD/node_modules/xclap
[10:04:12] NodeJS version v10.15.0 at /Users/c0r00jl/.nvm/versions/node/v10.15.0/bin/node
[10:04:12] CWD is /Users/wat/store-services/registry-web-ui
[10:04:12] Loaded CWD/xclap.js
[10:04:12] PATH already contains CWD/~/.bin
[10:04:12] NOTE: finally hook is unreliable when stopOnError is set to full
[10:04:12] Process dev's dependency serial array [".remove-log-files",".development-env",".mk-dist-dir",".build.client.babelrc",".build.server.babelrc"]
[10:04:12] -Execute electrode/.remove-log-files as function
[10:04:12] >Done Execute electrode/.remove-log-files as function (0 ms)
[10:04:12] .Execute electrode/.development-env as function
[10:04:12] >Done Execute electrode/.development-env as function (0 ms)
[10:04:12] -Execute electrode/.mk-dist-dir as function
[10:04:12] >Done Execute electrode/.mk-dist-dir as function (0 ms)
[10:04:12] .Execute electrode/.build.client.babelrc as function
info: You have old /Users/wat/store-services/registry-web-ui/src/client/.babelrc - please remove it to allow .babelrc.js.
[10:04:12] >Done Execute electrode/.build.client.babelrc as function (3 ms)
[10:04:12] -Execute electrode/.build.server.babelrc as function
info: You have old /Users/wat/store-services/registry-web-ui/src/server/.babelrc - please remove it to allow .babelrc.js.
[10:04:12] >Done Execute electrode/.build.server.babelrc as function (1 ms)
[10:04:12] Done Process dev's dependency serial array [".remove-log-files",".development-env",".mk-dist-dir",".build.client.babelrc",".build.server.babelrc"] (6 ms)
[10:04:12] Execute electrode/dev as function
[10:04:12] -Process electrode/dev.fR concurrent array [".set.css-module.env",".webpack-dev",["wds.dev","server-watch ","generate-service-worker"]]
[10:04:12] ..Execute electrode/.set.css-module.env as function
[10:04:12] --Execute electrode/.webpack-dev as function
[10:04:12] ..Process electrode/dev.fR.C concurrent array ["wds.dev","server-watch ","generate-service-worker"]
[10:04:12] >>Done Execute electrode/.set.css-module.env as function (1 ms)
[10:04:12] >>Done Execute electrode/.webpack-dev as function (0 ms)
[10:04:12] ---Execute electrode/generate-service-worker as function
[10:04:12] ...Process server-watch's dependency serial array [".init-bundle.valid.log"]
[10:04:12] >>>Done Execute electrode/generate-service-worker as function (1 ms)
[10:04:12] ----Execute electrode/.init-bundle.valid.log as function
[10:04:12] >>>>Done Execute electrode/.init-bundle.valid.log as function (1 ms)
[10:04:12] >>>Done Process server-watch's dependency serial array [".init-bundle.valid.log"] (2 ms)
[10:04:12] ...Execute electrode/server-watch as function
[10:04:12] ---Execute electrode/wds.dev webpack-dev-server --watch --watch-aggregate-timeout 2000 --hot --config "CWD/~/electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js" --progress --colors --port 2992 --host localhost
[10:04:12] ....Execute nodemon  -C --delay 1 --ext js,jsx,json,yaml,log,ts,tsx --watch .etmp/bundle.valid.log --watch config --watch src/server --exec node "CWD/~/electrode-archetype-react-app/support/babel-run" src/server
[nodemon] 1.18.10
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/wat/store-services/registry-web-ui/config/**/* /Users/wat/store-services/registry-web-ui/src/server/**/*
info: No custom webpack config webpack.config.dev.js found in dirs CWD; CWD/archetype/config/webpack
info: No custom entry point configuration /Users/wat/store-services/registry-web-ui/src/client/entry.config.js
info: No subapps found under src
info: Default to single app entry point using ./app.js under context /Users/wat/store-services/registry-web-ui/src/client
isomorphic-loader webpack plugin: removed existing config file
error: uncaughtException: Cannot find module 'electrode-archetype-opt-pwa' 
{ date: 'Sat Mar 09 2019 10:04:14 GMT-0800 (Pacific Standard Time)',
  process:
   { pid: 5298,
     uid: 463990172,
     gid: 74715970,
     cwd: '/Users/wat/store-services/registry-web-ui',
     execPath: '/Users/c0r00jl/.nvm/versions/node/v10.15.0/bin/node',
     version: 'v10.15.0',
     argv:
      [ '/Users/c0r00jl/.nvm/versions/node/v10.15.0/bin/node',
        '/Users/wat/store-services/registry-web-ui/node_modules/electrode-archetype-react-app-dev/node_modules/.bin/webpack-dev-server',
        '--watch',
        '--watch-aggregate-timeout',
        '2000',
        '--hot',
        '--config',
        '/Users/wat/store-services/registry-web-ui/node_modules/electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js',
        '--progress',
        '--colors',
        '--port',
        '2992',
        '--host',
        'localhost' ],
     memoryUsage:
      { rss: 124907520,
        heapTotal: 96243712,
        heapUsed: 71094720,
        external: 98629 } },
  os:
   { loadavg: [ 1.736328125, 1.75048828125, 1.83837890625 ],
     uptime: 177549 },
  trace:
   [ { column: 15,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._resolveFilename',
       line: 581,
       method: '_resolveFilename',
       native: false },
     { column: 19,
       file: 'internal/modules/cjs/helpers.js',
       function: 'Function.resolve',
       line: 32,
       method: 'resolve',
       native: false },
     { column: 38,
       file:
        '/Users/wat/store-services/registry-web-ui/node_modules/electrode-archetype-react-app-dev/config/webpack/partial/pwa.js',
       function: null,
       line: 14,
       method: null,
       native: false },
     { column: 30,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._compile',
       line: 689,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._extensions..js',
       line: 700,
       method: '.js',
       native: false },
     { column: 32,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.load',
       line: 599,
       method: 'load',
       native: false },
     { column: 12,
       file: 'internal/modules/cjs/loader.js',
       function: 'tryModuleLoad',
       line: 538,
       method: null,
       native: false },
     { column: 3,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module._load',
       line: 530,
       method: '_load',
       native: false },
     { column: 17,
       file: 'internal/modules/cjs/loader.js',
       function: 'Module.require',
       line: 637,
       method: 'require',
       native: false },
     { column: 18,
       file: 'internal/modules/cjs/helpers.js',
       function: 'require',
       line: 22,
       method: null,
       native: false } ],
  stack:
   [ 'Error: Cannot find module \'electrode-archetype-opt-pwa\'',
     '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)',
     '    at Function.resolve (internal/modules/cjs/helpers.js:32:19)',
     '    at Object.<anonymous> (/Users/wat/store-services/registry-web-ui/node_modules/electrode-archetype-react-app-dev/config/webpack/partial/pwa.js:14:38)',
     '    at Module._compile (internal/modules/cjs/loader.js:689:30)',
     '    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)',
     '    at Module.load (internal/modules/cjs/loader.js:599:32)',
     '    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)',
     '    at Function.Module._load (internal/modules/cjs/loader.js:530:3)',
     '    at Module.require (internal/modules/cjs/loader.js:637:17)',
     '    at require (internal/modules/cjs/helpers.js:22:18)' ] }
[10:04:14] >>>Failed Execute electrode/wds.dev webpack-dev-server --watch --watch-aggregate-timeout 2000 --hot --config "CWD/~/electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js" --progress --colors --port 2992 --host localhost (1.71 sec)
[10:04:14] >>>>Done Execute nodemon  -C --delay 1 --ext js,jsx,json,yaml,log,ts,tsx --watch .etmp/bundle.valid.log --watch config --watch src/server --exec node "CWD/~/electrode-archetype-react-app/support/babel-run" src/server (1.73 sec)
[10:04:14] >>>Done Execute electrode/server-watch as function (1.75 sec)
[10:04:14] >>Done Process electrode/dev.fR.C concurrent array ["wds.dev","server-watch ","generate-service-worker"] (1.75 sec)
[10:04:14] >Done Process electrode/dev.fR concurrent array [".set.css-module.env",".webpack-dev",["wds.dev","server-watch ","generate-service-worker"]] (1.75 sec)
[10:04:14] Done Execute electrode/dev as function (1.75 sec)
 Execution Failed - Errors: 
 1  shell cmd 'webpack-dev-server --watch --watch-aggregate-timeout 2000 --hot --config "/Users/wat/store-services/registry-web-ui/node_modules/electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js" --progress --colors --port 2992 --host localhost' exit code 1
```

**Comment by swashcap** [comment]
Attempting to install the dependency yields errors:

```shell
$ npm i -D electrode-archetype-opt-pwa

> @walmart/electrode-opt-webapp@1.0.0 preinstall /Users/wat/store-services/registry-web-ui/node_modules/@walmart/electrode-opt-webapp
> node opt-check.js

@walmart/electrode-opt-webapp: @walmart/electrode-react-webapp2 not detected in config/default.js,config/default.json - not installing

> electrode-archetype-opt-pwa@1.0.1 preinstall /Users/wat/store-services/registry-web-ui/node_modules/electrode-archetype-opt-pwa
> node optional-check.js

electrode-archetype-opt-pwa: skipping install because archetype/config set options.pwa to false

> electrode-archetype-opt-sass@1.0.4 preinstall /Users/wat/store-services/registry-web-ui/node_modules/electrode-archetype-opt-sass
> node optional-check.js

electrode-archetype-opt-sass: archetype config set sass to false - skipping install because it's not true

npm WARN @walmart/electrode-wml-server@4.7.3 requires a peer of @walmart/electrode-log-consumer@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN karma-webpack@4.0.0-rc.3 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optimize-css-assets-webpack-plugin@5.0.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN terser-webpack-plugin@1.2.3 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN webpack-cli@3.2.3 requires a peer of webpack@4.x.x but none is installed. You must install peer dependencies yourself.
npm WARN webpack-dev-middleware@3.6.1 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @walmart/electrode-opt-webapp@1.0.0 (node_modules/@walmart/electrode-opt-webapp):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @walmart/electrode-opt-webapp@1.0.0 preinstall: `node opt-check.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electrode-archetype-opt-pwa@1.0.1 preinstall: `node optional-check.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electrode-archetype-opt-pwa@1.0.1 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

> electrode-archetype-opt-inferno@0.2.6 preinstall /Users/wat/store-services/registry-web-ui/node_modules/electrode-archetype-opt-inferno
> node optional-check.js

electrode-archetype-opt-inferno: archetype config set reactLib to undefined - skipping install because it's not inferno

> @walmart/opt-electrode-server-2@1.2.2 preinstall /Users/wat/store-services/registry-web-ui/node_modules/@walmart/opt-electrode-server-2
> node check.js


npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/wat/.npm/_logs/2019-03-09T18_07_47_581Z-debug.log
```

**Comment by swashcap** [comment]
FYI, archetype config:

```shell
$ cat archetype/config.js
module.exports = {
  options: {
    cssModule: false,
    sass: false,
    pwa: false
  }
};
```

**Comment by swashcap** [comment]
Looks like any pre-install errors are swallowed: https://github.com/electrode-io/electrode/blob/3c54ce0e0742b39f101158d0c5cc2474cc5978ff/packages/electrode-archetype-opt-pwa/optional-check.js#L40

**Comment by swashcap** [comment]
Looks like the `pwa: false` config causes this. Opened a PR to address the issue: #1169.

The workaround:

```shell
$ git diff -U0 -- archetype/config.js
diff --git a/archetype/config.js b/archetype/config.js
index 2569781..7bd354e 100644
--- a/archetype/config.js
+++ b/archetype/config.js
@@ -5 +4,0 @@ module.exports = {
-    pwa: false
```

**Comment by swashcap** [comment]
Looks like Webpack now fails:

```shell
Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.                                           
 - configuration has an unknown property 'optimization'. These properties are valid:                                                                                  
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }                          
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.                                                                                 
     Loaders should be updated to allow passing options via loader options in module.rules.                                                                           
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:                                                               
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           optimization: ...
         }
       })
     ]
[10:46:40] >>>Failed Execute electrode/wds.dev webpack-dev-server --watch --watch-aggregate-timeout 2000 --hot --config "CWD/~/electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js" --progress --colors --port 2992 --host localhost (2.14 sec)
```

Looks like the solution in #1079 (upgrade to `webpack@^4`) totally works! 🎉

**Comment by swashcap** [comment]
Looks like `electrode-archetype-opt-pwa` is an optional dependency for `electrode-archetype-react-app-dev`:

https://github.com/electrode-io/electrode/blob/3c54ce0e0742b39f101158d0c5cc2474cc5978ff/packages/electrode-archetype-react-app-dev/package.json#L142

I'm not sure there's anything else actionable on this issue, so closing it.
