### ISSUE TITLE
Electrode Redux Router Engine and React Router Dom 4.4.0 / 5.0

### ISSUE THREAD

**Issue by brandonburkett** [electrode-io/electrode#1178]
## Type of issue
Bug (maybe) 

----

## My environment

* *OS version/details*: `macOS 10.14.3`
* *Node version:* `11.10.1`
* *npm version:* `6.7.0`

## Current behavior
This is more of a heads up, but react-router-dom published 4.4.0 today and npm outdated bumped the version (electrode-redux-router-engine also uses ^4.3.1).  Using this version causes a SSR routing issue.  It has since been pulled and re-released as 5.0.0.

I believe that react-router-dom and react-router-config will need to be updated to 5.0.0 at some point for electrode-redux-router-engine.

## Steps to reproduce the behavior
Get accidentally upgraded to react-router-dom 4.4.0 before it was unpublished.  Rolling and pinning to react-router-dom 4.3.1

## Command line output

This is what happens after a fresh `ignite` with 4.4.0 / 5.0.0.
```
electrode-redux-router-engine Error: Error: Invariant failed: You should not use <Route> outside a <Router>
    at invariant (/Users/bburkett/git/_test/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:13:11)
    at Object.children (/Users/bburkett/git/_test/node_modules/react-router-dom/node_modules/react-router/cjs/react-router.js:454:21)
    at ReactDOMServerRenderer.render (/Users/bburkett/git/_test/node_modules/react-dom/cjs/react-dom-server.node.development.js:3395:55)
    at ReactDOMServerRenderer.read (/Users/bburkett/git/_test/node_modules/react-dom/cjs/react-dom-server.node.development.js:3144:29)
    at renderToStaticMarkup (/Users/bburkett/git/_test/node_modules/react-dom/cjs/react-dom-server.node.development.js:3644:27)
    at ReduxRouterEngine._renderToString (/Users/bburkett/git/_test/node_modules/electrode-redux-router-engine/lib/redux-router-engine.js:253:93)
    at ReduxRouterEngine._handleRender (/Users/bburkett/git/_test/node_modules/electrode-redux-router-engine/lib/redux-router-engine.js:233:21)
    at ReduxRouterEngine.render (/Users/bburkett/git/_test/node_modules/electrode-redux-router-engine/lib/redux-router-engine.js:109:25)
```

For my project specifically, I was getting
```
Invariant Violation: You should not use <Switch> outside a <Router>
```

**Comment by brandonburkett** [comment]
React Router issue on this topic: https://github.com/ReactTraining/react-router/issues/6630
