### ISSUE TITLE
Electrode fails to build production on Koa/Express

### ISSUE THREAD

**Issue by jazzywhit** [electrode-io/electrode#1198]
## Type of issue

Bug

----

## My environment

* *OS version/details*: `OSX 10.14.3`
* *Node version:* `v11.11.0`
* *npm version:* `6.7.0` (run `npm --version` in your terminal)
* *Version of yo :* `2.0.5` (run `yo --version` in your terminal)

## Expected behavior

Projects using Koa or Express should build without errors.

## Current behavior

Building fails to complete because of an error on both Koa and Express servers. Hapi server seems to work fine.

In Hapi.js it doesn't look like the app-dev-middleware setup() function is called which is where the error is coming from.

## Steps to reproduce the behavior

Create a new project using Koa or Express for the server
`ignite generate-app`

Run your app in production mode
`NODE_ENV=production clap -n -x electrode/build prod`

## Command line output

Error that I receive:

```
stack:
   [ 'TypeError: process.send is not a function',
     '    at Timeout.setTimeout [as _onTimeout] (../node_modules/electrode-archetype-react-app-dev/lib/app-dev-middleware.js:62:15)',
     '    at listOnTimeout (timers.js:327:15)',
     '    at processTimers (timers.js:271:5)' ] }
```

`console.log(process)` in the parent function

```
process {
  title: 'node',
  version: 'v11.11.0',
  versions:
   { node: '11.11.0',
     v8: '7.0.276.38-node.18',
     uv: '1.26.0',
     zlib: '1.2.11',
     brotli: '1.0.7',
     ares: '1.15.0',
     modules: '67',
     nghttp2: '1.34.0',
     napi: '4',
     llhttp: '1.1.1',
     http_parser: '2.8.0',
     openssl: '1.1.1a',
     cldr: '34.0',
     icu: '63.1',
     tz: '2018e',
     unicode: '11.0' },
  arch: 'x64',
  platform: 'darwin',
  release:
   { name: 'node',
     sourceUrl:
      'https://nodejs.org/download/release/v11.11.0/node-v11.11.0.tar.gz',
     headersUrl:
      'https://nodejs.org/download/release/v11.11.0/node-v11.11.0-headers.tar.gz' },
  argv:
   [ '/usr/local/Cellar/node/11.11.0/bin/node',
     '../lib/server' ],
  execArgv: [],
  env:
   { NODE_ENV: 'production',
     ENABLE_SHORTEN_CSS_NAMES: 'true',
     TERM_PROGRAM: 'iTerm.app',
     SHELL: '/bin/bash',
     TERM: 'xterm-256color',
     TMPDIR: '',
     Apple_PubSub_Socket_Render: '/private/tmp/com.apple.launchd.6amPpcpYtV/Render',
     TERM_PROGRAM_VERSION: '3.2.8',
     TERM_SESSION_ID: ',
     USER: '',
     SSH_AUTH_SOCK: '/private/tmp/com.apple.launchd.TWZDW6txiZ/Listeners',
     __CF_USER_TEXT_ENCODING: '0x1F5:0x0:0x0',
     PATH:
      '../node_modules/electrode-archetype-react-app/node_modules/.bin:../taulah/taulah-web/node_modules/electrode-archetype-react-app-dev/node_modules/.bin:../taulah/taulah-web/node_modules/.bin:../miniconda2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin',
     PWD: './',
     LANG: 'en_US.UTF-8',
     ITERM_PROFILE: 'Default',
     XPC_FLAGS: '0x0',
     FORCE_COLOR: 'true',
     XPC_SERVICE_NAME: '0',
     COLORFGBG: '7;0',
     HOME: './',
     SHLVL: '2',
     SERVER_ES6: 'true',
     ENABLE_CSS_MODULE: 'true',
     ITERM_SESSION_ID: '',
     LOGNAME: '',
     WEBPACK_DEV_MIDDLEWARE: 'true',
     ENABLE_KARMA_COV: 'false',
     COLORTERM: 'truecolor',
     _: '/usr/local/bin/node',
     APP_SRC_DIR: 'lib/' },
  pid: 2965,
  ppid: 2964,
  execPath: '/usr/local/Cellar/node/11.11.0/bin/node',
  debugPort: 9229,
  _rawDebug: [Function: _rawDebug],
  moduleLoadList:
   [ 'Internal Binding module_wrap',
     'Internal Binding native_module',
     'Internal Binding config',
     'NativeModule internal/util',
     'NativeModule internal/errors',
     'Internal Binding buffer',
     'Internal Binding constants',
     'Internal Binding util',
     'NativeModule internal/util/types',
     'Internal Binding types',
     'NativeModule events',
     'NativeModule buffer',
     'NativeModule internal/util/inspect',
     'NativeModule internal/validators',
     'NativeModule internal/buffer',
     'Internal Binding icu',
     'NativeModule internal/process/per_thread',
     'NativeModule util',
     'NativeModule internal/encoding',
     'NativeModule internal/process/main_thread_only',
     'Internal Binding process_methods',
     'NativeModule internal/process/warning',
     'NativeModule internal/process/next_tick',
     'Internal Binding task_queue',
     'NativeModule internal/process/promises',
     'NativeModule internal/async_hooks',
     'NativeModule internal/options',
     'Internal Binding options',
     'Internal Binding async_wrap',
     'NativeModule internal/fixed_queue',
     'Internal Binding credentials',
     'NativeModule internal/process/stdio',
     'NativeModule internal/inspector_async_hook',
     'Internal Binding inspector',
     'NativeModule internal/console/global',
     'NativeModule internal/console/constructor',
     'Internal Binding trace_events',
     'NativeModule internal/util/inspector',
     'NativeModule internal/url',
     'NativeModule internal/querystring',
     'NativeModule internal/constants',
     'NativeModule path',
     'Internal Binding url',
     'NativeModule timers',
     'Internal Binding timers',
     'NativeModule internal/linkedlist',
     'NativeModule internal/priority_queue',
     'NativeModule internal/timers',
     'NativeModule internal/domexception',
     'Internal Binding messaging',
     'NativeModule internal/process/execution',
     'NativeModule internal/bootstrap/pre_execution',
     'NativeModule internal/modules/cjs/loader',
     'NativeModule vm',
     'Internal Binding contextify',
     'NativeModule internal/assert',
     'NativeModule fs',
     'Internal Binding fs',
     'NativeModule internal/fs/utils',
     'NativeModule internal/modules/cjs/helpers',
     'NativeModule url',
     'NativeModule internal/idna',
     'Internal Binding signal_wrap',
     'NativeModule assert',
     'NativeModule internal/assert/assertion_error',
     'NativeModule module',
     'NativeModule crypto',
     'Internal Binding crypto',
     'NativeModule internal/crypto/random',
     'NativeModule internal/crypto/pbkdf2',
     'NativeModule internal/crypto/util',
     'NativeModule internal/crypto/scrypt',
     'NativeModule internal/crypto/keygen',
     'NativeModule internal/crypto/keys',
     'NativeModule internal/crypto/diffiehellman',
     'NativeModule internal/crypto/cipher',
     'NativeModule internal/streams/lazy_transform',
     'NativeModule stream',
     'NativeModule internal/streams/pipeline',
     'NativeModule internal/streams/end-of-stream',
     'NativeModule internal/streams/legacy',
     'NativeModule _stream_readable',
     'NativeModule internal/streams/buffer_list',
     'NativeModule internal/streams/destroy',
     'NativeModule internal/streams/state',
     'NativeModule _stream_writable',
     'NativeModule _stream_duplex',
     'NativeModule _stream_transform',
     'NativeModule _stream_passthrough',
     'NativeModule internal/crypto/sig',
     'NativeModule internal/crypto/hash',
     'NativeModule internal/crypto/certificate',
     'NativeModule string_decoder',
     'Internal Binding string_decoder',
     'Internal Binding tty_wrap',
     'NativeModule tty',
     'NativeModule net',
     'NativeModule internal/net',
     'Internal Binding uv',
     'Internal Binding stream_wrap',
     ... 22 more items ],
  binding: [Function: binding],
  _linkedBinding: [Function: _linkedBinding],
  _events:
   [Object: null prototype] {
     warning: [Function: onWarning],
     newListener: [Function: startListeningIfSignal],
     removeListener: [Function: stopListeningIfSignal],
     SIGINT: [Function],
     SIGWINCH: [ [Function], [Function] ],
     uncaughtException: [Function: bound ] },
  _eventsCount: 6,
  _maxListeners: undefined,
  domain: null,
  _exiting: false,
  config:
   { target_defaults:
      { cflags: [],
        default_configuration: 'Release',
        defines: [],
        include_dirs: [Array],
        libraries: [Array] },
     variables:
      { asan: 0,
        build_v8_with_gn: false,
        coverage: false,
        debug_nghttp2: false,
        enable_lto: false,
        enable_pgo_generate: false,
        enable_pgo_use: false,
        force_dynamic_crt: 0,
        host_arch: 'x64',
        icu_gyp_path: 'tools/icu/icu-system.gyp',
        icu_small: false,
        icu_ver_major: '63',
        llvm_version: '0',
        node_byteorder: 'little',
        node_debug_lib: false,
        node_enable_d8: false,
        node_enable_v8_vtunejit: false,
        node_experimental_http_parser: false,
        node_install_npm: false,
        node_module_version: 67,
        node_no_browser_globals: false,
        node_prefix: '/usr/local/Cellar/node/11.11.0',
        node_release_urlbase: '',
        node_report: true,
        node_shared: false,
        node_shared_cares: false,
        node_shared_http_parser: false,
        node_shared_libuv: false,
        node_shared_nghttp2: false,
        node_shared_openssl: false,
        node_shared_zlib: false,
        node_tag: '',
        node_target_type: 'executable',
        node_use_bundled_v8: true,
        node_use_dtrace: true,
        node_use_etw: false,
        node_use_large_pages: false,
        node_use_openssl: true,
        node_use_pch: false,
        node_use_v8_platform: true,
        node_with_ltcg: false,
        node_without_node_options: false,
        openssl_fips: '',
        openssl_is_fips: false,
        shlib_suffix: '67.dylib',
        target_arch: 'x64',
        v8_enable_gdbjit: 0,
        v8_enable_i18n_support: 1,
        v8_enable_inspector: 1,
        v8_no_strict_aliasing: 1,
        v8_optimized_debug: 1,
        v8_promise_internal_field_count: 1,
        v8_random_seed: 0,
        v8_trace_maps: 0,
        v8_use_snapshot: true,
        want_separate_host_toolset: 0,
        xcode_version: '10.0' } },
  abort: [Function: abort],
  umask: [Function: umask],
  chdir: [Function],
  _debugProcess: [Function: _debugProcess],
  _debugEnd: [Function: _debugEnd],
  _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
  _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
  cwd: [Function],
  dlopen: [Function: dlopen],
  uptime: [Function: uptime],
  _getActiveRequests: [Function: _getActiveRequests],
  _getActiveHandles: [Function: _getActiveHandles],
  reallyExit: [Function: reallyExit],
  _kill: [Function: _kill],
  hrtime: { [Function: hrtime] bigint: [Function: hrtimeBigInt] },
  cpuUsage: [Function: cpuUsage],
  memoryUsage: [Function: memoryUsage],
  kill: [Function: kill],
  exit: [Function: exit],
  emitWarning: [Function: emitWarning],
  nextTick: [Function: nextTick],
  _tickCallback: [Function: runNextTicks],
  getuid: [Function: getuid],
  geteuid: [Function: geteuid],
  getgid: [Function: getgid],
  getegid: [Function: getegid],
  getgroups: [Function: getgroups],
  initgroups: [Function: initgroups],
  setgroups: [Function: setgroups],
  setegid: [Function],
  seteuid: [Function],
  setgid: [Function],
  setuid: [Function],
  stdout: [Getter],
  stderr: [Getter],
  stdin: [Getter],
  openStdin: [Function],
  argv0: 'node',
  allowedNodeEnvironmentFlags: [Getter/Setter],
  assert: [Function: deprecated],
  features:
   { inspector: true,
     debug: false,
     uv: true,
     ipv6: true,
     tls_alpn: true,
     tls_sni: true,
     tls_ocsp: true,
     tls: true },
  _fatalException: [Function],
  setUncaughtExceptionCaptureCallback: [Function: setUncaughtExceptionCaptureCallback],
  hasUncaughtExceptionCaptureCallback: [Function: hasUncaughtExceptionCaptureCallback],
  mainModule:
   Module {
     id: '.',
     exports: [Function],
     parent: null,
     filename: '../lib/server/index.js',
     loaded: true,
     children: [ [Module], [Module], [Module] ],
     paths:[] } }
```

**Comment by jazzywhit** [comment]
I tested the fix in the referenced commits and launching in production works as expected.

What is the normal release process once fixes like that get into master? @jchip
