### ISSUE TITLE
Failed to compile/start after pulling latest for universal-react-node.

### ISSUE THREAD

**Issue by thejones** [electrode-io/electrode#152]
Failed to start after pulling latest for ```universal-react-node```. I believe that the client and server directories were moved into a src directory which may be part of this. Please let me know if you need any other information. 

running ```gulp dev```.

```universal-react-node master % gulp dev
[11:54:17] Using gulpfile ~/dev/thejones/learnelectrode/electrode/samples/universal-react-node/gulpfile.js
[11:54:17] Starting 'dev'...
[11:54:17] Starting '.webpack-dev'...
[11:54:17] Finished '.webpack-dev' after 299 μs
[11:54:17] Starting 'server-dev'...
[11:54:17] Starting 'server-watch-$deps$'...
[11:54:17] Starting '.init-bundle.valid.log'...
[11:54:17] Finished '.init-bundle.valid.log' after 1.25 ms
[11:54:17] Finished 'server-watch-$deps$' after 3.71 ms
[11:54:17] Starting 'server-watch'...
[11:54:17] Starting 'generate-service-worker'...
[11:54:17] Finished 'generate-service-worker' after 563 μs
  Usage: nodemon [nodemon options] [script.js] [args]

  See "nodemon --help" for more.

[11:54:18] Finished 'server-watch' after 682 ms
Entry point configuration is not found, using default entry point...
isomorphic-loader webpack plugin: removed existing config file
  0% compileError
    at Compilation.<anonymous> (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/lib/Compilation.js:358:28)
    at onDoneResolving (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/tapable/lib/Tapable.js:134:6
resolve file
  /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/client/images/electrode.png doesn't exist
  /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/client/images/electrode.png.js doesn't exist
  /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/client/images/electrode.png.jsx doesn't exist
resolve directory
  /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/client/images/electrode.png doesn't exist (directory default file)
  /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/client/images/electrode.png/package.json doesn't exist (directory description file)
 http://localhost:2992/webpack-dev-server/
webpack result is served from http://localhost:2992/js/
content is served from /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node
```

running ```NODE_ENV=development gulp hot```

```
universal-react-node master % NODE_ENV=development gulp hot
[11:56:26] Using gulpfile ~/dev/thejones/learnelectrode/electrode/samples/universal-react-node/gulpfile.js
[11:56:26] Starting 'hot'...
[11:56:26] Starting '.webpack-dev'...
[11:56:26] Finished '.webpack-dev' after 268 μs
[11:56:26] Starting 'server-hot'...
[11:56:26] Starting 'server-watch-$deps$'...
[11:56:26] Starting '.init-bundle.valid.log'...
[11:56:26] Finished '.init-bundle.valid.log' after 1.22 ms
[11:56:26] Finished 'server-watch-$deps$' after 3.69 ms
[11:56:26] Starting 'server-watch'...
[11:56:26] Starting 'generate-service-worker'...
[11:56:26] Finished 'generate-service-worker' after 595 μs
  Usage: nodemon [nodemon options] [script.js] [args]

  See "nodemon --help" for more.

[11:56:26] Finished 'server-watch' after 708 ms
Entry point configuration is not found, using default entry point...
isomorphic-loader webpack plugin: removed existing config file
 70% 2/2 build modulesError
    at Compilation.<anonymous> (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/lib/Compilation.js:358:28)
    at onDoneResolving (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/lib/NormalModuleFactory.js:29:20)
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/lib/NormalModuleFactory.js:85:20
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:726:13
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:723:17
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/webpack/node_modules/async/lib/async.js:167:37
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:24:19
    at onResolved (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/Resolver.js:38:18)
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/Resolver.js:127:10
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/Resolver.js:110:4)
    at loggingCallbackWrapper (/Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/enhanced-resolve/lib/createInnerCallback.js:21:19)
    at /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/node_modules/tapable/lib/Tapable.js:134:6
resolve file
  /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/client/images/electrode.png doesn't exist
  /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/client/images/electrode.png.js doesn't exist
  /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/client/images/electrode.png.jsx doesn't exist
resolve directory
  /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/client/images/electrode.png doesn't exist (directory default file)
  /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node/client/images/electrode.png/package.json doesn't exist (directory description file)
 http://localhost:2992/
webpack result is served from http://localhost:2992/js/
content is served from /Users/turnagain/dev/thejones/learnelectrode/electrode/samples/universal-react-node
 70% 80/80 build modules
```

**Comment by jchip** [comment]
All the packages and samples in the latest HEAD are always updated to work with each other.  To try them with the published packages, you have to checkout by the published tags.

To run everything with latest HEAD, see here https://github.com/electrode-io/electrode/blob/master/contributing.md#getting-started.
