### ISSUE TITLE
`clap features` crashes from electrode X calls

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1546]
## Type

Bug :bug:

## My environment

* *OS version/details*: osx, mojave
* *Node version:* 12
* *npm version:* 6
* *Version of yo :* n/a

## Expected behavior

- no crash

## Current behavior

- crash

## Steps to reproduce the behavior

```
$ npx clap features
```

## Command line output

```
$ npx clap features
[11:17:12] NOTE: finally hook is unreliable when stopOnError is set to full
[11:17:12] Execute electrode/features as function
[11:17:12] Failed Execute electrode/features as function (1 ms)
 Execution Failed - Errors:
 1  Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at getFeatures (/Users/c0d01a5/src/storks/node_modules/@xarc/app/lib/features.js:285:27)
    at Object.displayFeatures (/Users/c0d01a5/src/storks/node_modules/@xarc/app/lib/features.js:455:26)
    at XQtor._functionXer (/Users/c0d01a5/src/storks/node_modules/xclap/lib/xqtor.js:574:39)
    at XQtor._processTaskObject (/Users/c0d01a5/src/storks/node_modules/xclap/lib/xqtor.js:257:19)
    at XQtor.execute (/Users/c0d01a5/src/storks/node_modules/xclap/lib/xqtor.js:99:21)
    at XQtor._next (/Users/c0d01a5/src/storks/node_modules/xclap/lib/xqtor.js:55:12)
    at /Users/c0d01a5/src/storks/node_modules/xclap/lib/xqtor.js:44:33
    at processTicksAndRejections (internal/process/task_queues.js:83:21)
```

```json5
// package.json
{
  "name": "storks",
  "version": "0.0.1",
  "description": "",
  "homepage": "",
  "scripts": {
    ...
  },
  "contributors": [],
  "main": "lib/server/index.js",
  "keywords": [
    "electrode",
    "web"
  ],
  "repository": {
    "type": "git",
    "url": ""
  },
  "license": "UNLICENSED",
  "engines": {
    "node": ">= 10",
    "npm": ">= 6"
  },
  "dependencies": {
    "@walmart/*****": "***",
    "@xarc/app": "^8.0.1",
    "bluebird": "^2",
    "classnames": "^2.2.6",
    "electrode-server": "^3.0.0",
    "exenv": "^1.2.0",
    "fecha": "^2.3.0",
    "fs-extra": "^0.26.5",
    "good-file": "^6.0.1",
    "good-squeeze": "^5.1.0",
    "good": "^7.3.0",
    "http-status-codes": "^1.3.0",
    "isomorphic-loader": "^2.1.1",
    "lodash": "^4.17.15",
    "memcache-client-memoizer": "2.2.0",
    "memcache-client": "0.10.0",
    "prop-types": "^15.6.2",
    "react-dom": "^16",
    "react-intl": "^2.4.0",
    "react-redux": "^7.1.1",
    "react-router-redux": "^4.0.8",
    "react-router": "^3.2.1",
    "react-visibility-sensor": "^4.1.0",
    "react": "^16",
    "redux-thunk": "^2.3.0",
    "redux": "^4.0.4",
    "scroll-into-view-if-needed": "^2.2.20",
    "subapp-react": "~0.0.4",
    "subapp-redux": "^1.0.13",
    "subapp-server": "^1.1.5"
  },
  "devDependencies": {
    "@babel/preset-typescript": "^7.8.3",
    "@types/hapi__hapi": "^19.0.2",
    "@types/hapi__joi": "^16.0.12",
    "@types/klaw": "^3.0.0",
    "@types/node": "^13.7.7",
    "@types/react": "^16.9.23",
    "@types/react-dom": "^16.9.5",
    "@xarc/app-dev": "^8.0.1",
    "del-cli": "^3.0.0",
    "klaw": "^3.0.0",
    "npm-run-all": "^4.1.5",
    "typescript": "^3.8.2"
  }
}
```

**Comment by cdaringe** [comment]
@christianlent, how can i get the new bits?

**Comment by christianlent** [comment]
Good question! It looks like the new @xarc/app (https://www.npmjs.com/package/@xarc/app/v/8.0.6) was released 3 days ago - I'm assuming that has the above fix. Make sure your @xarc/app and @xarc/app-dev are both on 8.0.6 (`"^8.0.6"`) in `package.json`. If that doesn't work, please ping me and we'll get it figured out right away.
