### ISSUE TITLE
subapp-web: dangerously falls back onerror when downstream code expects non-error condition

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1558]
## Type of issue

bug 🐛 

## My environment

n/a

## Expected behavior

- tbd

## Current behavior

here's the flow:

```js
// node_modules/subapp-web/lib/util.js
  loadAssetsFromStats(statsPath) {
    let stats;

    try {
      // stats path currently "dist/server/stats.json", which is non-existant
      stats = JSON.parse(Fs.readFileSync(Path.resolve(statsPath)).toString());
    } catch (err) {
      return {};
    }

// node_modules/subapp-web/lib/init.js
  const { assets } = util.loadAssetsFromStats(setupContext.routeOptions.stats);
  // assets is now _undefined_
  const cdnJsBundles = util.getCdnJsBundles(assets, setupContext.routeOptions);

// back in util
  getCdnJsBundles(assets, routeOptions, cdnAssetsFile) {
   // ...
    const {
      chunksById: { js, css }
    } = assets; // still undefined
```

💣 error! but unhandled error

## Steps to reproduce the behavior

- clone the storks project, @ 9ebe6c95593c3b5e8b886e64477ee9ac8270d6e7
- npm install
- `node --inspect ./node_modules/@xarc/app/support/babel-run src/server/index.ts`
- on boot, visit localhost:3000
- observe the failure mode

## Command line output

```
Unhandled rejection TypeError: Cannot read property 'chunksById' of undefined
    at Object.getCdnJsBundles (/Users/c0d01a5/src/storks/node_modules/subapp-web/lib/util.js:167:9)
    at setup (/Users/c0d01a5/src/storks/node_modules/subapp-web/lib/init.js:26:29)
    at Token.load (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/token.js:58:21)
    at JsxRenderer._applyTokenLoad (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:199:10)
    at JsxRenderer.setupTokenInst (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:235:10)
    at processToken (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/process-token.js:12:30)
    at Object.Require [as type] (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/Require.js:6:10)
    at JsxRenderer._render (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:179:25)
    at nextChild (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:114:32)
    at nextChild (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:119:20)
    at nextChild (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:119:20)
    at nextChild (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:119:20)
    at nextChild (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:119:20)
    at nextChild (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:119:20)
From previous event:
    at nextChild (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:117:28)
    at handleElementChildren (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:124:23)
    at JsxRenderer._render (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:183:12)
    at /Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:56:24
    at processImmediate (internal/timers.js:439:21)
From previous event:
    at JsxRenderer.render (/Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/jsx/JsxRenderer.js:56:8)
    at /Users/c0d01a5/src/storks/node_modules/electrode-react-webapp/lib/react-webapp.js:117:26
    at handler (/Users/c0d01a5/src/storks/node_modules/subapp-server/lib/setup-hapi-routes.js:180:31)
    at module.exports.internals.Manager.execute (/Users/c0d01a5/src/storks/node_modules/@hapi/hapi/lib/toolkit.js:41:33)
    at Object.internals.handler (/Users/c0d01a5/src/storks/node_modules/@hapi/hapi/lib/handler.js:46:48)
    at exports.execute (/Users/c0d01a5/src/storks/node_modules/@hapi/hapi/lib/handler.js:31:36)
    at Request._lifecycle (/Users/c0d01a5/src/storks/node_modules/@hapi/hapi/lib/request.js:312:68)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at Request._execute (/Users/c0d01a5/src/storks/node_modules/@hapi/hapi/lib/request.js:221:9)```

**Comment by cdaringe** [comment]
Looks like #1557, but the problems stated are unique and likely ought have unique solutions
