### ISSUE TITLE
dev-admin: periodic crashes from node runtime

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/electrode#1565]
## Type of issue

bug :bug:

## My environment

- OS: macOS catalina
- node 12.x

## Expected behavior

no crashes

## Current behavior

crashes

## Steps to reproduce the behavior

not deterministic. knowing that we use chokidar to restart things, i wonder if maybe https://github.com/paulmillr/chokidar/issues/612#issuecomment-378026034 is relevant?

## Command line output

```
Assertion failed: (handle->flags & UV_HANDLE_CLOSING), function uv__finish_close, file ../deps/uv/src/unix/core.c, line 257.
...
 Execution Failed - Errors: 
 1  cmd "node "/Users/c0d01a5/src/storks/node_modules/electrode-archetype-react-app-dev/lib/dev-admin"  --exec "/Users/c0d01a5/src/storks/node_modules/electrode-archetype-react-app/support/babel-run" --ext js,jsx,json,yaml,log,ts,tsx --watch config src/server -- src/server" exit code null
    at ChildProcess.<anonymous> (/Users/c0d01a5/src/storks/node_modules/xclap/lib/xqtor.js:477:23)
    at ChildProcess.emit (events.js:210:5)
    at maybeClose (internal/child_process.js:1028:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
```

**Comment by jchip** [comment]
I've never seen this.  More context on the OS version might help.

**Comment by cdaringe** [comment]
agreed--not sure why i left those out! posted above
