### ISSUE TITLE
demo app and component: gulp check fails

### ISSUE THREAD

**Issue by DavidOrchard** [electrode-io/electrode#197]
In the generic demo application such as `https://github.com/DavidOrchard/electrodeDemo`

```
L-SB890WSFFT-M:electrodeDemo dorchar$ gulp check

/Users/dorchar/code/workspace/electrodeDemo/node_modules/electrode-archetype-react-app/arch-gulpfile.js:3
const Fs = require("fs");
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/dorchar/code/workspace/electrodeDemo/gulpfile.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Is there an eslint config missing?

**Comment by jchip** [comment]
please check your node version.  that file does have "use strict" on top which should work for node 4.2 and up.  node 6 and up supports these even w/o the "use strict" now.
