### ISSUE TITLE
gulp check fails on newly created component

### ISSUE THREAD

**Issue by thehogfather** [electrode-io/electrode#285]
genetor-electrode version 1.10.0

Steps
* run `yo electrode:component`
After installation and setup cd into the component directory and run `gulp check`.

Here is a stack trace of the error - It looks as though the string `'eslint-config-'` is prepended to the archetype names extended in the `.eslintrc` file:

```sh
[10:06:52] Using gulpfile ~/Documents/workspace/failing-test/gulpfile.js
[10:06:52] Starting 'check'...
[10:06:52] Starting 'check-dep'...
Check dependencies passed
[10:06:52] Finished 'check-dep' after 193 ms
[10:06:52] Starting 'lint'...
[10:06:52] Starting 'lint-react-demo'...
The react/wrap-multilines rule is deprecated. Please use the react/jsx-wrap-multilines rule instead.
[10:06:53] Finished 'lint-react-demo' after 973 ms
[10:06:53] Starting 'lint-react-src'...
The react/wrap-multilines rule is deprecated. Please use the react/jsx-wrap-multilines rule instead.
[10:06:54] Finished 'lint-react-src' after 1.04 s
[10:06:54] Starting 'lint-react-test'...
Cannot find module 'eslint-config-electrode-archetype-react-component/config/eslint/.eslintrc-react-test'
Referenced from: /Users/patrick/Documents/workspace/failing-test/test/client/.eslintrc
Error: Cannot find module 'eslint-config-electrode-archetype-react-component/config/eslint/.eslintrc-react-test'
Referenced from: /Users/patrick/Documents/workspace/failing-test/test/client/.eslintrc
    at ModuleResolver.resolve (/Users/patrick/Documents/workspace/failing-test/node_modules/eslint/lib/util/module-resolver.js:74:19)
    at resolve (/Users/patrick/Documents/workspace/failing-test/node_modules/eslint/lib/config/config-file.js:515:25)
    at load (/Users/patrick/Documents/workspace/failing-test/node_modules/eslint/lib/config/config-file.js:532:26)
    at configExtends.reduceRight (/Users/patrick/Documents/workspace/failing-test/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/patrick/Documents/workspace/failing-test/node_modules/eslint/lib/config/config-file.js:408:28)
    at Object.load (/Users/patrick/Documents/workspace/failing-test/node_modules/eslint/lib/config/config-file.js:566:22)
    at loadConfig (/Users/patrick/Documents/workspace/failing-test/node_modules/eslint/lib/config.js:63:33)
    at getLocalConfig (/Users/patrick/Documents/workspace/failing-test/node_modules/eslint/lib/config.js:130:29)
    at Config.getConfig (/Users/patrick/Documents/workspace/failing-test/node_modules/eslint/lib/config.js:260:26)
```
Expectation is that tests pass on a freshly generated component project.

Contents of `failing-test/test/client/.eslintrc`

```js
---
extends:
  - "electrode-archetype-react-component/config/eslint/.eslintrc-react-test"
```

**Comment by didi0613** [comment]
PR out is here: https://github.com/electrode-io/electrode/pull/291
Thanks for bringing this one out 👍
