### ISSUE TITLE
Undefined errors when running coverage tests on component projects

### ISSUE THREAD

**Issue by thehogfather** [electrode-io/electrode#286]
generator-electrode version 1.10.0

Steps
* Run `yo electrode:component`
* Modify `.eslintrc` file in `test/client/.eslintrc` to contain `  - "../../node_modules/electrode-archetype-react-component/config/eslint/.eslintrc-react-test"` instead of   `- "electrode-archetype-react-component/config/eslint/.eslintrc-react-test"` (This is a workaround for #285)
* Run `gulp check`

See stack trace of error below:

```sh
[10:22:48] Using gulpfile ~/Documents/workspace/failing-test/gulpfile.js
[10:22:48] Starting 'check'...
[10:22:48] Starting 'check-dep'...
Check dependencies passed
[10:22:48] Finished 'check-dep' after 193 ms
[10:22:48] Starting 'lint'...
[10:22:48] Starting 'lint-react-demo'...
The react/wrap-multilines rule is deprecated. Please use the react/jsx-wrap-multilines rule instead.
[10:22:49] Finished 'lint-react-demo' after 1.19 s
[10:22:49] Starting 'lint-react-src'...
The react/wrap-multilines rule is deprecated. Please use the react/jsx-wrap-multilines rule instead.
[10:22:50] Finished 'lint-react-src' after 1.01 s
[10:22:50] Starting 'lint-react-test'...
The react/wrap-multilines rule is deprecated. Please use the react/jsx-wrap-multilines rule instead.
[10:22:51] Finished 'lint-react-test' after 1.01 s
[10:22:51] Starting 'lint-scripts'...
[10:22:52] Finished 'lint-scripts' after 548 ms
[10:22:52] Finished 'lint' after 3.76 s
[10:22:52] Starting 'test-cov'...
[10:22:52] Starting 'test-frontend-cov'...
18 04 2017 10:22:54.012:ERROR [config]: Invalid config file!
  ReferenceError: coverageProfile is not defined
    at makeConfig (/Users/patrick/Documents/workspace/failing-test/node_modules/electrode-archetype-react-component/config/webpack/webpack.config.coverage.js:27:20)
    at Object.<anonymous> (/Users/patrick/Documents/workspace/failing-test/node_modules/electrode-archetype-react-component/config/webpack/webpack.config.coverage.js:36:18)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/patrick/Documents/workspace/failing-test/node_modules/electrode-archetype-react-component/config/karma/karma.conf.coverage.js:8:21)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
[10:22:54] 'test-frontend-cov' errored after 1.49 s
[10:22:54] Error: command exit code 1
    at error (/Users/patrick/Documents/workspace/failing-test/node_modules/electrode-gulp-helper/lib/exec.js:6:15)
    at shell.exec (/Users/patrick/Documents/workspace/failing-test/node_modules/electrode-gulp-helper/lib/exec.js:39:29)
    at /Users/patrick/Documents/workspace/failing-test/node_modules/shelljs/src/exec.js:204:9
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[10:22:54] 'check' errored after 5.44 s
[10:22:54] Error in plugin 'run-sequence(test-frontend-cov)'
Message:
    command exit code 1
[10:22:54] 'test-cov' errored after 1.49 s
[10:22:54] Error in plugin 'run-sequence(check)'
Message:
    command exit code 1
[10:22:54] 'test-cov' errored after 1.49 s
[10:22:54] Error in plugin 'run-sequence(test-frontend-cov)'
Message:
    command exit code 1
```
These errors can be addressed locally by patching the local files:
* `node_modules/electrode-archetype-react-component/config/webpack/webpack.config.coverage.js`
* `node_modules/electrode-archetype-react-component/config/webpack/partial/coverage.js`

**Comment by dzuluagae** [comment]
We're experiencing the same issue.
This PR is probably what broke the check task:
https://github.com/electrode-io/electrode/commit/afc5216c1692788078e0d3c203e9c3de6db4bad7

**Comment by dzuluagae** [comment]
I ran into the same problem. This is probably the PR that broke the check task: https://github.com/electrode-io/electrode/commit/21cfa175c318287a19731a969d99e990477eb2b7

**Comment by animesh10** [comment]
Thanks for the investigation and PR!

**Comment by thehogfather** [comment]
no problem.

**Comment by didi0613** [comment]
@thehogfather @dzuluagae  Thank you for pointing this out and thanks for the PR 👍 
i am currently working on this issue and it may expecting more changes. Will let you know once the fixes PR is created.

**Comment by didi0613** [comment]
@thehogfather PR is out here: https://github.com/electrode-io/electrode/pull/291 Thanks!

**Comment by dzuluagae** [comment]
thank you @didi0613 !
