### ISSUE TITLE
Error in plugin 'run-sequence(wds.dev)'

### ISSUE THREAD

**Issue by jgknott** [electrode-io/electrode#295]
I'm just trying to get the demo app up and running.  I went through the yo generator, npm install, and finally gulp dev which produces the following: (Note: I've tried node 6.6.0 and 6.10.0)

```
[10:59:45] 'wds.dev' errored after 1.33 s
[10:59:45] Error: command exit code 1
    at error (/electrode-gulp-helper/lib/exec.js:6:15)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
[10:59:45] 'dev' errored after 1.34 s
[10:59:45] Error in plugin 'run-sequence(wds.dev)'
Message:
    command exit code 1
```

Any ideas?

**Comment by animesh10** [comment]
Hi, 
I will try to reproduce this issue.
What were the options you selected for the serverType and the PWA(progressive WebApp) ?

**Comment by knilink** [comment]
I think the issue was in electrode-webpack-reporter/lib/webpack-reporter.js line 43
`.replace(/{{SOCKET_PORT}}/g, options.socketPort)`
should be
`.replace(/{{SOCKET_PORT}}/g, this.options.socketPort)`

a temporary workaround is to disable html webpack reporter
`export HTML_WEBPACK_REPORTER_OFF=1;gulp dev`

**Comment by animesh10** [comment]
Yes that's exactly it, I have raised a PR for the same.

**Comment by jgknott** [comment]
Yep that fixed it, thanks!

**Comment by sandelld** [comment]
+1 - same issue, updating the file with workaround fixed. thanks

**Comment by kwafarkye** [comment]
had the same issue too and editing line 43 in `electrode-webpack-reporter/lib/webpack-reporter.js` fixed it.

**Comment by Alchemist-V** [comment]
Ran into this issue, thanks @knilink for the workaround.
