### ISSUE TITLE
Heroku Deployment - App Crashes

### ISSUE THREAD

**Issue by Gattermeier** [electrode-io/electrode#308]
Following the get started instructions the app crashes in production mode on Heroku. 
Log dump: 
```
Starting standalone server in PROD mode
info: APP_SRC_DIR set to lib/

ESERVERSTART
Invalid options value: must be true, falsy or an object

Unhandled rejection Error: Invalid options value: must be true, falsy or an object

at Object.exports.assert (/app/node_modules/hapi/node_modules/hoek/lib/index.js:736:11)
at Object.exports.applyToDefaults (/app/node_modules/hapi/node_modules/hoek/lib/index.js:154:13)
at concat.forEach (/app/node_modules/hapi/lib/server.js:159:37)
at Array.forEach (native)
at module.exports.internals.Server.internals.Server.connection (/app/node_modules/hapi/lib/server.js:156:24)
at _.each (/app/node_modules/electrode-server/lib/electrode-server.js:109:14)
at /app/node_modules/lodash/lodash.js:4944:15
at baseForOwn (/app/node_modules/lodash/lodash.js:3001:24)
at /app/node_modules/lodash/lodash.js:4913:18
at Function.forEach (/app/node_modules/lodash/lodash.js:9359:14)
at setConnections (/app/node_modules/electrode-server/lib/electrode-server.js:103:7)
at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)
at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:512:31)
at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:569:18)
at Promise._settlePromiseCtx (/app/node_modules/bluebird/js/release/promise.js:606:10)
at Async._drainQueue (/app/node_modules/bluebird/js/release/async.js:138:12)
```

**Comment by animesh10** [comment]
Is this happening only on heroku ? does your app successfully run after `gulp build` && `gulp server` on your local ?

**Comment by Gattermeier** [comment]
That's correct. The app (really, just the boilerplate with a couple of react components) runs as expected with `gulp build` && `gulp server` locally

**Comment by animesh10** [comment]
Okay, we'll take a look what changed

**Comment by animesh10** [comment]
I am not able to recreate this with the getting started app, generated by `yo electrode`. Looking at the logs, could you try setting `heroku config:set NPM_CONFIG_PRODUCTION=false` and `heroku config:set STATIC_FILES_OFF=true` as suggested by the getting started instructions.
