### ISSUE TITLE
Error: Cannot find module '../archetype/config.js' --- yo electrode:component, during 'build-dist-dev'...

### ISSUE THREAD

**Issue by guymorita** [electrode-io/electrode#324]
Version 1.12

```
森田:guymorita:/Users/guymorita/Projects/electrode_lab yo electrode:component

Welcome to the Electrode Component Generator

We're going to set up a new Electrode component, ready for development with
gulp, webpack, demo, electrode component archetype, and live-reload
? What is your Package/GitHub project name? (e.g., 'wysiwyg-component') wysiwyg-component
? What is the ClassName for your component?
? What will be the npm package name? elect
? What will be the GitHub organization username (e.g., 'walmartlabs')?
? What is your name? (for copyright notice, etc.) Guy Morita
? What is your GitHub Username? Guy Morita
? Use double quotes or single quotes? "
? What is the name of the GitHub repo where this will be published?
? Would you like to create a new directory for your project? Yes
   create .babelrc
   create .gitignore
   create .npmignore
   create .editorconfig
   create gulpfile.js
   create package.json
   create README.md
   create src/components/wysiwyg-component.jsx
   create src/styles/wysiwyg-component.css
   create src/lang/default-messages.js
   create src/lang/en.json
   create src/lang/tenants/electrodeio/default-messages.js
   create src/index.js
   create test/client/.eslintrc
   create test/client/components/wysiwyg-component.spec.jsx
   create test/client/components/helpers/intl-enzyme-test-helper.js
   create demo/demo.jsx
   create demo/demo.css
   create demo/examples/wysiwyg-component.example
npm WARN deprecated isparta-loader@2.0.0: Package is deprecated, use https://github.com/deepsweet/istanbul-instrumenter-loader
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> dtrace-provider@0.8.1 install /Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/dtrace-provider
> node scripts/install.js


> fsevents@1.1.1 install /Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/fsevents
> node install

[fsevents] Success: "/Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/fsevents/lib/binding/Release/node-v51-darwin-x64/fse.node" is installed via remote

> phantomjs-prebuilt@2.1.14 install /Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-macosx.zip
Saving to /var/folders/q8/nv8mt5s94kn9nwcgqc6tf4br0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Receiving...
  [========================================] 100%
Received 16746K total.
Extracting zip contents
Removing /Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/q8/nv8mt5s94kn9nwcgqc6tf4br0000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1494190635997/phantomjs-2.1.1-macosx -> /Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> history@1.17.0 postinstall /Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/history
> node ./npm-scripts/postinstall.js


> component-playground@1.3.2 postinstall /Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/component-playground
> node -e "require('fs').stat('lib', function(e,s){process.exit(e || !s.isDirectory() ? 1 : 0)})" || npm run build-lib


> wysiwyg-component@1.0.0 prepublish /Users/guymorita/Projects/electrode_lab/wysiwyg-component
> gulp prepublish

[13:57:18] Using gulpfile ~/Projects/electrode_lab/wysiwyg-component/gulpfile.js
[13:57:18] Starting 'prepublish'...
[13:57:18] Starting 'npm:prepublish'...
[13:57:18] Starting 'build-lib-$deps$'...
[13:57:18] Starting '~production-env'...
[13:57:18] Finished '~production-env' after 124 μs
[13:57:18] Finished 'build-lib-$deps$' after 996 μs
[13:57:18] Starting 'build-lib'...
[13:57:18] Starting 'clean-lib'...
[13:57:18] Finished 'clean-lib' after 3.04 ms
[13:57:18] Starting 'babel-src-step'...
src/components/wysiwyg-component.jsx -> lib/components/wysiwyg-component.js
src/index.js -> lib/index.js
src/lang/default-messages.js -> lib/lang/default-messages.js
src/lang/tenants/electrodeio/default-messages.js -> lib/lang/tenants/electrodeio/default-messages.js
[13:57:19] Finished 'babel-src-step' after 712 ms
[13:57:19] Starting 'build-lib:flatten-l10n'...
[13:57:19] Finished 'build-lib:flatten-l10n' after 246 ms
[13:57:19] Starting 'build-lib:copy-flow'...
[13:57:19] Finished 'build-lib:copy-flow' after 79 ms
[13:57:19] Starting 'build-lib:clean-tmp'...
[13:57:19] Finished 'build-lib:clean-tmp' after 2.95 ms
[13:57:19] Finished 'build-lib' after 1.04 s
[13:57:19] Starting 'build-dist-dev'...
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/guymorita/Projects/electrode_lab/wysiwyg-component/archetype/config.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/electrode-archetype-react-component/config/webpack/partial/styles.js:16:16)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/electrode-archetype-react-component/config/webpack/webpack.config.js:9:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
[13:57:20] 'build-dist-dev' errored after 695 ms
[13:57:20] Error: command exit code 1
    at error (/Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/electrode-gulp-helper/lib/exec.js:6:15)
    at shell.exec (/Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/electrode-gulp-helper/lib/exec.js:39:29)
    at /Users/guymorita/Projects/electrode_lab/wysiwyg-component/node_modules/shelljs/src/exec.js:204:9
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
[13:57:20] 'prepublish' errored after 1.74 s
[13:57:20] Error in plugin 'run-sequence(build-dist-dev)'
Message:
    command exit code 1
[13:57:20] 'npm:prepublish' errored after 1.74 s
[13:57:20] Error in plugin 'run-sequence(prepublish)'
Message:
    command exit code 1
[13:57:20] 'npm:prepublish' errored after 1.74 s
[13:57:20] Error in plugin 'run-sequence(build-dist-dev)'
Message:
    command exit code 1

npm WARN wysiwyg-component@1.0.0 No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! wysiwyg-component@1.0.0 prepublish: `gulp prepublish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the wysiwyg-component@1.0.0 prepublish script 'gulp prepublish'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the wysiwyg-component package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp prepublish
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs wysiwyg-component
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls wysiwyg-component
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/guymorita/Projects/electrode_lab/wysiwyg-component/npm-debug.log

Your new Electrode component is ready!

Your component is in src/ and your demo files are in demo/

Type 'cd wysiwyg-component' then 'gulp demo' to run the development build and demo tasks.
```

**Comment by animesh10** [comment]
Thanks for reporting this, our newest version of `electrode-archetype-react-component` will take care of this. Updating your `package.json` with `electrode-archetype-react-component@^2.0.0` should fix it for now.

**Comment by guymorita** [comment]
@animesh10 Thanks for getting back. You mean after the installation errors out? The package.json is already targeting electrode-archetype-react-component@^2.0.0. This is the package.json after yo electrode:component:

```
{
  "name": "wysiwyg-component",
  "version": "1.0.0",
  "description": "wysiwyg-component",
  "main": "lib/index.js",
  "author": {
    "name": "",
    "url": "https://github.com/"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com//.git"
  },
  "bugs": {
    "url": "https://github.com///issues"
  },
  "homepage": "https://github.com//",
  "dependencies": {},
  "devDependencies": {
    "electrode-archetype-react-component": "^2.0.0",
    "electrode-archetype-react-component-dev": "^1.0.0",
    "gulp": "^3.9.1"
  },
  "engines": {
    "node": "^4.2.6",
    "npm": "^3.5.3"
  },
  "scripts": {
    "prepublish": "gulp prepublish",
    "start": "gulp demo",
    "test": "gulp check"
  },
  "keywords": [
    "react",
    "electrode",
    "electrode-component",
    "react-component"
  ]
}
```

**Comment by guymorita** [comment]
Any further suggestions?

**Comment by animesh10** [comment]
Version 1.12.0 doesn't yet use `electrode-archetype-react-component@2.0.0`. 
Anyways, your `electrode-archetype-react-component-dev` should also point to `v2.0.0`.

**Comment by guymorita** [comment]
@animesh10 Thanks. Because of the error I don't think the installation is completing. I changed to version 2.0.0 after the install, and ran npm install.

```
森田:guymorita:/Users/guymorita/Projects/elec_comp/wysiwyg-component gulp demo
[11:43:08] Using gulpfile ~/Projects/elec_comp/wysiwyg-component/gulpfile.js
[11:43:08] Task 'demo' is not in your gulpfile
[11:43:08] Please check the documentation for proper gulpfile formatting
```

gulpfile.js
```
"use strict";



/**
 * There is a full range of gulp tasks defined in the above archetype
 * but below is a concise list of most often used gulp tasks at the
 * component level
 *
 * Full list of gulp tasks:
 * https://github.com/electrode-io/electrode-archetype-react-component/blob/master/archetype-gulpfile.js#L38-L134
 *
 */

const tasks = {

  "prepublish": ["npm:prepublish"],

};

require("electrode-archetype-react-component")(tasks);
```

**Comment by guymorita** [comment]
@animesh10 Here is the repo if it helps. I'll be working with Electrode @ Walmart so your help is much appreciated. https://github.com/guymorita/wysiwyg-component

**Comment by animesh10** [comment]
Thanks for using Electrode! The `gulp demo` not working is just a side-effect of the major version upgrade of the component. A major overhaul of the `electrode component` is about to be published, which no longer uses the demo task.
For a simpler fix, i would recommend locking in the `electrode-archetype-react-component` and `electrode-archetype-react-component-dev` versions to `v1.3.0` and using `gulp open-dev`.
BTW, this is just the demo feature, your component is still fully functional and present under `src`.

**Comment by guymorita** [comment]
@animesh10 Great, I'll try that out shortly.

**Comment by guymorita** [comment]
Looks good! Thanks

![image](https://cloud.githubusercontent.com/assets/2003939/25825622/7d243b0e-33f8-11e7-9b4c-e89557e87047.png)
