### ISSUE TITLE
Getting started issues

### ISSUE THREAD

**Issue by mcrowder65** [electrode-io/electrode#446]
- Test components
   Under the test components section, running npm test fails. See issue:
     `Cannot read config file: /Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/node_modules/electrode-archetype-react-component/config/eslint/.eslintrc-react
Error: ENOENT: no such file or directory, open '/Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/node_modules/electrode-archetype-react-component/config/eslint/.eslintrc-react'
Referenced from: /Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/.eslintrc
Error: Cannot read config file: /Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/node_modules/electrode-archetype-react-component/config/eslint/.eslintrc-react
Error: ENOENT: no such file or directory, open '/Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/node_modules/electrode-archetype-react-component/config/eslint/.eslintrc-react'
Referenced from: /Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/.eslintrc
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at readFile (/Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/node_modules/eslint/lib/config/config-file.js:70:24)
    at loadLegacyConfigFile (/Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/node_modules/eslint/lib/config/config-file.js:142:44)
    at loadConfigFile (/Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/node_modules/eslint/lib/config/config-file.js:241:22)
    at load (/Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/node_modules/eslint/lib/config/config-file.js:535:18)
    at configExtends.reduceRight.e (/Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/node_modules/eslint/lib/config/config-file.js:424:36)
    at Array.reduceRight (native)
    at applyExtends (/Users/mcrowder65/work/electrode-app-dir/components/custom-component/packages/custom-component/node_modules/eslint/lib/config/config-file.js:408:28)
[09:23:23] >>Failed Execute ext/lint-react-src eslint --ext .js,.jsx -c ./.eslintrc src --color (420 ms)
[09:23:23] >Done Process electrode/lint serial array ["lint-react-src","lint-react-test","lint-scripts"] (421 ms)
[09:23:23] Done Process electrode/check serial array ["check-dep","lint","test-cov","build-lib:clean-tmp"] (652 ms)
 Execution Failed - Errors:
 1  shell cmd 'eslint --ext .js,.jsx -c ./.eslintrc src --color' exit code 1`
- Under the 'Add your routes' section, it instructs, `npm i your-awesome-published-npm-module --save`.. when we never published any modules..

**Comment by jchip** [comment]
Thanks for reporting the issue.  We will look into it.

**Comment by didi0613** [comment]
@mcrowder65 Hi Matt,
The docs have been updated. And we have few more updates to make it more clear. Thanks for pointing this out.
