### ISSUE TITLE
clap build error

### ISSUE THREAD

**Issue by zbrukas** [electrode-io/electrode#495]
Cmd: clap build
Log: 
```
ERROR in Entry module not found: Error: Cannot resolve 'file' or 'directory' ./app.js in /Users/zbrukas/workspace/personal/src/client
[15:45:28] >>Failed Execute electrode/build-dist-min webpack --config ~/node_modules/electrode-archetype-react-app-dev/config/webpack/webpack.config.js --colors (1.78 sec)
[15:45:28] >Done Process electrode/build-dist serial array [".clean.build","build-dist-dll","build-dist-min","build-dist:flatten-l10n","build-dist:merge-isomorphic-assets","copy-dll","build-dist:clean-tmp"] (1.80 sec)
[15:45:28] Done Process electrode/build serial array ["build-dist",".build-lib","ss-prod-react",".check.top.level.babelrc"] (1.80 sec)
 Execution Failed - Errors: 
 1  shell cmd 'webpack --config /Users/zbrukas/workspace/personal/node_modules/electrode-archetype-react-app-dev/config/webpack/webpack.config.js --colors' exit code 1
```

clap dev works without problems. I don't have a custom webpack config for production, although I have one for development.

Custom webpack for dev:

```
const FaviconsWebpackPlugin = require('favicons-webpack-plugin');
const _ = require('lodash');

module.exports = function (composer, options, compose) {
  const config = compose();
  _.merge(config, {
    plugins: [
      new FaviconsWebpackPlugin({
        // Your source logo
        logo: './images/logo.png',
        // The prefix for all image files (might be a folder or a name)
        prefix: 'icons-[hash]/',
        // Emit all stats of the generated icons
        emitStats: false,
        // The name of the json containing all favicon information
        statsFilename: 'iconstats-[hash].json',
        // Generate a cache file with control hashes and
        // don't rebuild the favicons until those hashes change
        persistentCache: true,
        // Inject the html into the html-webpack-plugin
        inject: true,
        // favicon background color (see https://github.com/haydenbleasel/favicons#usage)
        background: '#fff',
        // favicon app title (see https://github.com/haydenbleasel/favicons#usage)
        title: 'Heber Nobre',

        // which icons should be generated (see https://github.com/haydenbleasel/favicons#usage)
        icons: {
          android: true,
          appleIcon: true,
          appleStartup: true,
          coast: false,
          favicons: true,
          firefox: true,
          opengraph: false,
          twitter: false,
          yandex: false,
          windows: false
        }
      })
    ]
  }, (a, b) => {
    return (Array.isArray(a) && Array.isArray(b))
      ? [].concat(a).concat(b)
      : undefined;
  });

  return config;
};
```

Although it doesn't do what's expected, it doesn't give errors either (on dev).

**Comment by animesh10** [comment]
Hi @zbrukas : What is the name of the above file ? 
Also, you will have an `archetype-debug.log` file generated in your app, could you check if the final webpack config generated is correct. I suspect the above config merge isn't happening correctly.

**Comment by zbrukas** [comment]
@animesh10 the file name is `webpack.config.dev.js`, and it's on the folder `archetype/config/webpack`. The log seems ok to me:

```
2017-07-26T14:12:10.108Z - info: Custom webpack config webpack.config.dev.js loaded from CWD\archetype\config\webpack
2017-07-26T14:12:10.379Z - info: Entry point configuration C:\Projects\Personal\personal\src\client\entry.config.js is not found, using default entry point...
2017-07-26T14:12:11.417Z - info: Not disabling NodeSourcePlugin.  NODE_ENV: 'development'
2017-07-26T14:12:11.423Z - verbose: Final Webpack config {
  "cache": true,
  "plugins": [
    {
      "options": {
        "prefix": "icons-[hash]/",
        "emitStats": true,
        "statsFilename": "iconstats-[hash].json",
        "persistentCache": true,
        "inject": true,
        "background": "#fff",
        "logo": "./images/logo.png",
        "title": "Heber Nobre",
        "icons": {
          "android": true,
          "appleIcon": true,
          "appleStartup": true,
          "coast": false,
          "favicons": true,
          "firefox": true,
          "opengraph": false,
          "twitter": false,
          "yandex": false,
          "windows": false
        }
      }
    },
    {
      "filename": "[name].style.[hash].css",
      "id": 1,
      "options": {},
      "__name": "ExtractTextPlugin"
    },
    {
      "options": {
        "size": 4000,
        "preserve": true
      },
      "__name": "CSSSplitWebpackPlugin"
    },
    {
      "options": {
        "options": {
          "context": "C:\\Projects\\Personal\\personal\\src",
          "stylus": {}
        },
        "test": {}
      },
      "__name": "LoaderOptionsPlugin"
    },
    {
      "opts": {
        "filename": "../server/stats.json",
        "fields": [
          "assetsByChunkName",
          "assets"
        ]
      },
      "__name": "StatsWriterPlugin"
    },
    {
      "config": {
        "valid": false
      },
      "options": {
        "assetsFile": "../isomorphic-assets.json",
        "webpackDev": {
          "url": "http://localhost:2992",
          "addUrl": false
        }
      },
      "__name": "IsomorphicLoaderPlugin"
    },
    {
      "definitions": {
        "process.env.NODE_ENV": "\"development\""
      },
      "__name": "DefinePlugin"
    },
    {
      "sourceMappingURLComment": "\n//# sourceMappingURL=[url]",
      "moduleFilenameTemplate": "webpack:///[resourcePath]",
      "fallbackModuleFilenameTemplate": "webpack:///[resourcePath]?[hash]",
      "options": {
        "sourceMapFilename": "[file].map"
      },
      "__name": "SourceMapDevToolPlugin"
    },
    {
      "filename": "[name].style.css",
      "id": 2,
      "options": {},
      "__name": "ExtractTextPlugin"
    },
    {
      "__name": "NoEmitOnErrorsPlugin"
    }
  ],
  "context": "C:\\Projects\\Personal\\personal\\src\\client",
  "entry": "./app.js",
  "output": {
    "path": "C:\\Projects\\Personal\\personal\\dist\\js",
    "pathinfo": false,
    "publicPath": "http://localhost:2992/js/",
    "chunkFilename": "[hash].[name].js",
    "filename": "[name].bundle.dev.js"
  },
  "resolve": {
    "alias": {},
    "modules": [
      "C:\\Projects\\Personal\\personal\\src",
      "C:\\Projects\\Personal\\personal"
    ],
    "plugins": [
      {
        "source": "module",
        "path": "node_modules",
        "target": "resolve"
      }
    ],
    "extensions": [
      ".js",
      ".jsx",
      ".json"
    ]
  },
  "resolveLoader": {
    "modules": [
      "C:\\Projects\\Personal\\personal\\lib",
      "C:\\Projects\\Personal\\personal"
    ],
    "plugins": [
      {
        "source": "module",
        "path": "node_modules",
        "target": "resolve"
      }
    ]
  },
  "module": {
    "rules": [
      {
        "test": {},
        "exclude": {},
        "use": [
          {
            "loader": "babel-loader"
          }
        ]
      },
      {
        "test": {},
        "loader": [
          {
            "loader": "C:\\Projects\\Personal\\personal\\node_modules\\extract-text-webpack-plugin\\loader.js",
            "options": {
              "omit": 1,
              "remove": true,
              "publicPath": ""
            }
          },
          {
            "loader": "C:\\Projects\\Personal\\personal\\node_modules\\style-loader\\index.js"
          },
          {
            "loader": "C:\\Projects\\Personal\\personal\\node_modules\\css-loader\\index.js?modules&localIdentName=[name]__[local]___[hash:base64:5]&-autoprefixer"
          },
          {
            "loader": "C:\\Projects\\Personal\\personal\\node_modules\\postcss-loader\\index.js"
          }
        ]
      },
      {
        "test": {},
        "use": [
          {
            "loader": "postcss-loader",
            "options": {
              "browsers": [
                "last 2 versions",
                "ie >= 9",
                "> 5%"
              ]
            }
          }
        ]
      },
      {
        "test": {},
        "use": [
          {
            "loader": "C:\\Projects\\Personal\\personal\\node_modules\\url-loader\\index.js",
            "options": {
              "limit": 1000,
              "mimetype": "application/font-woff"
            }
          },
          "C:\\Projects\\Personal\\personal\\node_modules\\isomorphic-loader\\index.js"
        ]
      },
      {
        "test": {},
        "use": [
          "C:\\Projects\\Personal\\personal\\node_modules\\file-loader\\index.js",
          "C:\\Projects\\Personal\\personal\\node_modules\\isomorphic-loader\\index.js"
        ]
      },
      {
        "test": {},
        "use": [
          {
            "loader": "C:\\Projects\\Personal\\personal\\node_modules\\electrode-cdn-file-loader\\index.js",
            "options": {
              "limit": 10000
            }
          },
          "C:\\Projects\\Personal\\personal\\node_modules\\isomorphic-loader\\index.js"
        ]
      }
    ]
  },
  "devServer": {
    "https": false,
    "disableHostCheck": true,
    "headers": {
      "Access-Control-Allow-Origin": "*"
    }
  }
}
```

Do I have to have an extra `webpack.config.js` apart from the dev config with the same added plugin?

**Comment by zbrukas** [comment]
@animesh10 Btw, I flagged iconstats to true on the plugin and it doesn't generate them either. Thanks for helping 😄

**Comment by zbrukas** [comment]
Modified the config to
```js
const FaviconsWebpackPlugin = require('favicons-webpack-plugin');
const _ = require('lodash');

module.exports = function (composer, options, compose) {
  const config = compose();
  _.merge(config, {
    resolve: {
      extensions: [...config.resolve.extensions, '.png']
    },
    plugins: [
      _.merge(new FaviconsWebpackPlugin({
          logo: './images/logo.png',
          emitStats: true,
          background: '#fff',
          title: 'Heber Nobre'
        }), {
        __name: 'FaviconsWebpackPlugin'
        })
    ]
  });

  return config;
};
```

Error now outputs
```
EntryModuleNotFoundError: Entry module not found: Error: Cannot resolve 'file' or 'directory' ./images/logo.png in C:\Project
s\Personal\personal\src\client
    at Compilation.<anonymous> (C:\Projects\Personal\personal\node_modules\webpack\lib\Compilation.js:360:28)
    at onDoneResolving (C:\Projects\Personal\personal\node_modules\webpack\lib\NormalModuleFactory.js:29:20)
    at C:\Projects\Personal\personal\node_modules\webpack\lib\NormalModuleFactory.js:85:20
    at C:\Projects\Personal\personal\node_modules\async\lib\async.js:726:13
    at C:\Projects\Personal\personal\node_modules\async\lib\async.js:52:16
    at done (C:\Projects\Personal\personal\node_modules\async\lib\async.js:241:17)
    at C:\Projects\Personal\personal\node_modules\async\lib\async.js:44:16
    at C:\Projects\Personal\personal\node_modules\async\lib\async.js:723:17
    at C:\Projects\Personal\personal\node_modules\async\lib\async.js:167:37
    at C:\Projects\Personal\personal\node_modules\webpack\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:24:19
    at onResolved (C:\Projects\Personal\personal\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:38:18)
    at C:\Projects\Personal\personal\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:127:10
    at C:\Projects\Personal\personal\node_modules\webpack\node_modules\enhanced-resolve\lib\Resolver.js:191:15
    at applyPluginsParallelBailResult.createInnerCallback.log (C:\Projects\Personal\personal\node_modules\webpack\node_module
s\enhanced-resolve\lib\Resolver.js:110:4)
    at loggingCallbackWrapper (C:\Projects\Personal\personal\node_modules\webpack\node_modules\enhanced-resolve\lib\createInn
erCallback.js:21:19)
    at C:\Projects\Personal\personal\node_modules\tapable\lib\Tapable.js:134:6
    at Tapable.<anonymous> (C:\Projects\Personal\personal\node_modules\webpack\node_modules\enhanced-resolve\lib\DirectoryDef
aultFilePlugin.js:25:12)
    at Storage.finished (C:\Projects\Personal\personal\node_modules\webpack\node_modules\enhanced-resolve\lib\CachedInputFile
System.js:38:16)
    at C:\Projects\Personal\personal\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:123:15)
resolve file
  C:\Projects\Personal\personal\src\client\images\logo.png.json doesn't exist
  C:\Projects\Personal\personal\src\client\images\logo.png.js doesn't exist
  C:\Projects\Personal\personal\src\client\images\logo.png.jsx doesn't exist
  C:\Projects\Personal\personal\src\client\images\logo.png.png doesn't exist
resolve directory
  C:\Projects\Personal\personal\src\client\images\logo.png\package.json doesn't exist (directory description file)
  C:\Projects\Personal\personal\src\client\images\logo.png is not a directory (directory default file)
```

**Comment by jchip** [comment]
favicons-webpack-plugin doesn't support webpack 2

**Comment by jchip** [comment]
there's a pending PR https://github.com/jantimon/favicons-webpack-plugin/pull/48

**Comment by jchip** [comment]
we have a private copy that supports webpack 2 https://github.com/electrode-io/electrode/tree/master/packages/electrode-archetype-react-app-dev/config/webpack/plugins/favicons

https://github.com/electrode-io/electrode/pull/187

**Comment by zbrukas** [comment]
Thanks @jchip. Changed it to:
```js
const FaviconsWebpackPlugin = require('electrode-archetype-react-app-dev/config/webpack/plugins/favicons');
const _ = require('lodash');

module.exports = function(composer, options, compose) {
  const config = compose();
  _.merge(config, {
    plugins: [
      new FaviconsWebpackPlugin({
        logo: './images/logo.png',
        emitStats: true,
        background: '#fff',
        title: 'Heber Nobre'
      })
    ]
  });

  return config;
};
```
Still giving the same error. What is weird is that I have that config for both dev config and build config, and dev doesn't give errors. Most of all, it outputs this on the reporter > legacy console (localhost:2992):

```
Hash: 3a7c957b04c6250dabba
Version: webpack 2.7.0
Time: 37387ms
                                                                         Asset       Size  Chunks             Chunk Names
icons-39284772083c984f12ca9624845cacda/apple-touch-startup-image-1182x2208.png     190 kB          [emitted]  
             icons-39284772083c984f12ca9624845cacda/apple-touch-icon-57x57.png    2.74 kB          [emitted]  
             icons-39284772083c984f12ca9624845cacda/apple-touch-icon-72x72.png    3.56 kB          [emitted]  
             icons-39284772083c984f12ca9624845cacda/apple-touch-icon-76x76.png    3.88 kB          [emitted]  
           icons-39284772083c984f12ca9624845cacda/apple-touch-icon-114x114.png    6.08 kB          [emitted]  
           icons-39284772083c984f12ca9624845cacda/apple-touch-icon-120x120.png    6.36 kB          [emitted]  
           icons-39284772083c984f12ca9624845cacda/apple-touch-icon-144x144.png    8.17 kB          [emitted]  
           icons-39284772083c984f12ca9624845cacda/apple-touch-icon-152x152.png    8.54 kB          [emitted]  
           icons-39284772083c984f12ca9624845cacda/apple-touch-icon-167x167.png    9.63 kB          [emitted]  
           icons-39284772083c984f12ca9624845cacda/apple-touch-icon-180x180.png    10.6 kB          [emitted]  
                   icons-39284772083c984f12ca9624845cacda/apple-touch-icon.png    10.6 kB          [emitted]  
       icons-39284772083c984f12ca9624845cacda/apple-touch-icon-precomposed.png    10.6 kB          [emitted]  
               icons-39284772083c984f12ca9624845cacda/android-chrome-36x36.png    1.53 kB          [emitted]  
               icons-39284772083c984f12ca9624845cacda/android-chrome-48x48.png    2.06 kB          [emitted]  
               icons-39284772083c984f12ca9624845cacda/android-chrome-72x72.png    3.33 kB          [emitted]  
               icons-39284772083c984f12ca9624845cacda/android-chrome-96x96.png    4.63 kB          [emitted]  
             icons-39284772083c984f12ca9624845cacda/android-chrome-144x144.png    7.94 kB          [emitted]  
             icons-39284772083c984f12ca9624845cacda/android-chrome-192x192.png    11.2 kB          [emitted]  
             icons-39284772083c984f12ca9624845cacda/android-chrome-256x256.png    14.3 kB          [emitted]  
             icons-39284772083c984f12ca9624845cacda/android-chrome-384x384.png    34.4 kB          [emitted]  
             icons-39284772083c984f12ca9624845cacda/android-chrome-512x512.png    59.9 kB          [emitted]  
                      icons-39284772083c984f12ca9624845cacda/favicon-16x16.png  585 bytes          [emitted]  
                      icons-39284772083c984f12ca9624845cacda/favicon-32x32.png    1.28 kB          [emitted]  
                            icons-39284772083c984f12ca9624845cacda/favicon.ico    33.3 kB          [emitted]  
                  icons-39284772083c984f12ca9624845cacda/firefox_app_60x60.png    5.29 kB          [emitted]  
                icons-39284772083c984f12ca9624845cacda/firefox_app_128x128.png    12.9 kB          [emitted]  
                icons-39284772083c984f12ca9624845cacda/firefox_app_512x512.png    84.1 kB          [emitted]  
  icons-39284772083c984f12ca9624845cacda/apple-touch-startup-image-320x460.png      25 kB          [emitted]  
  icons-39284772083c984f12ca9624845cacda/apple-touch-startup-image-640x920.png    75.9 kB          [emitted]  
 icons-39284772083c984f12ca9624845cacda/apple-touch-startup-image-640x1096.png    76.7 kB          [emitted]  
 icons-39284772083c984f12ca9624845cacda/apple-touch-startup-image-768x1004.png    93.5 kB          [emitted]  
 icons-39284772083c984f12ca9624845cacda/apple-touch-startup-image-748x1024.png      91 kB          [emitted]  
 icons-39284772083c984f12ca9624845cacda/apple-touch-startup-image-750x1294.png    96.5 kB          [emitted]  
             icons-39284772083c984f12ca9624845cacda/apple-touch-icon-60x60.png    2.89 kB          [emitted]  
icons-39284772083c984f12ca9624845cacda/apple-touch-startup-image-1242x2148.png     200 kB          [emitted]  
icons-39284772083c984f12ca9624845cacda/apple-touch-startup-image-1496x2048.png     268 kB          [emitted]  
icons-39284772083c984f12ca9624845cacda/apple-touch-startup-image-1536x2008.png     270 kB          [emitted]  
                          icons-39284772083c984f12ca9624845cacda/manifest.json     1.2 kB          [emitted]  
                        icons-39284772083c984f12ca9624845cacda/manifest.webapp  254 bytes          [emitted]  
                                 icons-39284772083c984f12ca9624845cacda/.cache    7.76 kB          [emitted]  
                                           iconstats-23f7b9c7c964d06676bd.json    7.63 kB          [emitted]  
                                          2a8692426549f8d76bf00312b85754b1.svg    7.62 kB          [emitted]  
                                          64500ae3815a2362cac249c3c9ff1ca1.svg    5.47 kB          [emitted]  
                                          0f16d3cac157db0b23b40c11f0864ecf.jpg    1.26 MB          [emitted]  
                                          4fb5e23cf48bd093236f053e52c7c035.svg    11.9 kB          [emitted]  
                                          8caeb8c6482f4cd449f901773eb88f1d.svg    9.26 kB          [emitted]  
                                          73809e46e0a2cabd2391f0d2d2c1e4bc.svg    13.5 kB          [emitted]  
                                          687ba60d01cfaef34ff55294a94c0977.svg    14.4 kB          [emitted]  
                                          4d77d91c907f82f1a3182376e12abfd7.svg    15.3 kB          [emitted]  
                                          87b5bd755180dc8cc624c404f8a23e40.svg    10.1 kB          [emitted]  
                                          9820a5c2523ea7392060ce728d153c0f.svg       8 kB          [emitted]  
                                          35bb7028d7a39ef0ed09e9256311b44e.svg    6.29 kB          [emitted]  
                                          d187ed8c54225a303455a7b6bfcea2e4.svg    11.4 kB          [emitted]  
                                          974cfa75dea3c52c02120c3a61053591.svg    7.95 kB          [emitted]  
                                          bfd8cd03220e805f762b28b00d427977.svg    13.3 kB          [emitted]  
                                          a65a6100170be221030542f7c82a17c9.svg    8.04 kB          [emitted]  
                                          6b79f357f6eeb09e1ad4dd1c888d9c79.svg    3.44 kB          [emitted]  
                                          1a57f0ec8385655a7fbb66b6453895d8.svg    7.49 kB          [emitted]  
                                          e16cb1ffff17a6e3f332f0bb283348c2.svg    7.11 kB          [emitted]  
                                          63fecde2d2317e7cd873959d5c7139e3.svg    5.42 kB          [emitted]  
                                          52295e078e362b80611b668cab4db169.svg    1.88 kB          [emitted]  
                                                            main.bundle.dev.js    8.52 MB       0  [emitted]  main
                                           main.style.3a7c957b04c6250dabba.css      50 kB       0  [emitted]  main
                                                                main.style.css    49.9 kB       0  [emitted]  main
                                                          ../server/stats.json     9.8 kB          [emitted]  
                                                     ../isomorphic-assets.json    1.88 kB          [emitted]  
chunk    {0} main.bundle.dev.js, main.style.3a7c957b04c6250dabba.css, main.style.css (main) 3.1 MB [rendered]
    [1] ./~/react/react.js 56 bytes {0} [built]
   [29] ./~/react-dom/index.js 59 bytes {0} [built]
  [392] ./~/react-redux/es/index.js 230 bytes {0} [built]
  [402] ./~/react-router/es/index.js 1.46 kB {0} [built]
  [445] ./src/client/app.js 1.79 kB {0} [built]
  [446] ./~/webpack-dev-server/client?http://localhost:2992 5.59 kB {0} [built]
  [468] ./src/client/reducers/index.js 274 bytes {0} [built]
  [470] ./src/client/routes.js 498 bytes {0} [built]
  [570] ./src/client/styles/base.css 41 bytes {0} [built]
 [1048] ./~/react-tap-event-plugin/src/injectTapEventPlugin.js 1.04 kB {0} [built]
 [1123] ./~/strip-ansi/index.js 161 bytes {0} [built]
 [1127] ./~/url/url.js 23.3 kB {0} [built]
 [1129] ./~/webpack-dev-server/client/overlay.js 3.6 kB {0} [built]
 [1133] (webpack)/hot/emitter.js 77 bytes {0} [built]
 [1134] multi ./~/webpack-dev-server/client?http://localhost:2992 ./app.js 40 bytes {0} [built]
     + 1120 hidden modules
```
But the favicon on `localhost:3000` doesn't change.

**Comment by rvanrooy** [comment]
@zbrukas Did you resolve this? I'm running into the same issue. Favicon loads fine on localhost:2992, but still overridden by the react favicon on :3000

**Comment by zbrukas** [comment]
No, I didn't solve it. I'm still faviconless.

**Comment by davidalee** [comment]
Has anyone been able to add a favicon to their electrode project?

**Comment by zbrukas** [comment]
If it's PWA I have no problem. If it's not, as I can't modify the manifest
or the document head, I couldn't figure it out.

**Comment by Chrischuck** [comment]
The following is working for me for production builds, not working for dev however...

```
const FaviconsWebpackPlugin = require('favicons-webpack-plugin');

module.exports = function (composer, options, compose) {
  const config = compose();


  const plugins = [
    new FaviconsWebpackPlugin({
      logo: __dirname + '/src/client/images/logo.png',
      prefix: 'icons-[hash]/',
      emitStats: true,
      statsFilename: '../server/iconstats.json',
      persistentCache: true,
      inject: false,
      background: '#FFFFFF',
      icons: {
        android: true,
        appleIcon: true,
        appleStartup: true,
        chrome: true,
        coast: false,
        favicons: true,
        firefox: true,
        opengraph: false,
        twitter: false,
        yandex: false,
        windows: false
      }
    })
  ]

  config.plugins =  mergePlugins(config.plugins, plugins)

  return config
};

function mergePlugins(initialPlugins, newPlugins) {
  const plugins = {}
  initialPlugins.forEach(plugin => plugins[plugin.constructor.name] = plugin)
  newPlugins.forEach(plugin => plugins[plugin.constructor.name] = plugin)
  return Object.values(plugins)
}
```

When you console log the dirname, you end up with this: `/Users/user/Documents/{root dir}/test` So I guess when clap builds, it moves everything it needs to a test folder...

On top of this, if you console log the original plugins in the config, you'll find that it uses the absolute path for the favicons plugin.

Hope this helps.
