### ISSUE TITLE
window is not defined on electrode server

### ISSUE THREAD

**Issue by zbrukas** [electrode-io/electrode#521]
## Type of issue

window is not defined on electrode server
----

## My environment

* *OS version/details*:  `Windows 10 64-bit`
* *Node version:* `6.9.1`
* *npm version:* `3.10.8`
* *Version of yo :* `2.0.0`

## Expected behavior

When importing visual libraries like `mo.js` or `snap.svg`, electrode server should start without errors.

## Current behavior

When importing visual libraries like `mo.js` or `snap.svg`, electrode server doesn't start, outputting an error that window is not defined (libraries use window methods for various purposes).

## Steps to reproduce the behavior

Install mo.js, and import it in a random component using this syntax:

`import mojs from 'mo-js'`

## Command line output

```
[nodemon] starting `babel-node src\server\index.js`
info: APP_SRC_DIR set to src/
info: OptimizeModulesForProduction - skipping since NODE_ENV !== "production"
 > isomorphic-loader extend require: webpack dev server mode - config is now valid.
Register plugins failed ReferenceError: window is not defined
    at Helpers.getPrefix (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:7043:15)
    at Helpers.vars (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:6871:25)
    at new Helpers (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:6866:11)
    at Object.<anonymous> (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:7519:6)
    at __webpack_require__ (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:30:30)
    at Object.<anonymous> (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:10463:11)
    at Object.<anonymous> (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:10607:31)
    at __webpack_require__ (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:30:30)
    at Object.<anonymous> (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:57:19)
    at __webpack_require__ (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:30:30)
    at C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:50:18
    at C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:53:10
    at webpackUniversalModuleDefinition (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:3:20)
    at Object.<anonymous> (C:\Projects\Personal\personal\node_modules\mo-js\build\mo.js:10:3)
    at Module._compile (module.js:570:32)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Projects\Personal\personal\node_modules\babel-register\lib\node.js:152:7)
From previous event:
    at Object.registerRoutes (C:\Projects\Personal\personal\node_modules\electrode-react-webapp\lib\hapi\index.js:12:6)
    at Object.target [as register] (C:\Projects\Personal\personal\node_modules\joi\lib\types\object\index.js:77:34)
    at each (C:\Projects\Personal\personal\node_modules\hapi\lib\plugin.js:310:14)
    at iterate (C:\Projects\Personal\personal\node_modules\items\lib\index.js:36:13)
    at done (C:\Projects\Personal\personal\node_modules\items\lib\index.js:28:25)
    at Object.StaticPaths (C:\Projects\Personal\personal\node_modules\electrode-static-paths\lib\plugin-static-paths.js:49:3)
    at Object.target [as register] (C:\Projects\Personal\personal\node_modules\joi\lib\types\object\index.js:77:34)
    at each (C:\Projects\Personal\personal\node_modules\hapi\lib\plugin.js:310:14)
    at iterate (C:\Projects\Personal\personal\node_modules\items\lib\index.js:36:13)
    at done (C:\Projects\Personal\personal\node_modules\items\lib\index.js:28:25)
    at Object.exports.register (C:\Projects\Personal\personal\node_modules\inert\lib\index.js:44:12)
    at Object.target [as register] (C:\Projects\Personal\personal\node_modules\joi\lib\types\object\index.js:77:34)
    at each (C:\Projects\Personal\personal\node_modules\hapi\lib\plugin.js:310:14)
    at iterate (C:\Projects\Personal\personal\node_modules\items\lib\index.js:36:13)
    at Object.exports.serial (C:\Projects\Personal\personal\node_modules\items\lib\index.js:39:9)
    at internals.Plugin.register (C:\Projects\Personal\personal\node_modules\hapi\lib\plugin.js:313:11)
    at Promise (C:\Projects\Personal\personal\node_modules\electrode-server\lib\electrode-server.js:118:14)
From previous event:
    at registerPlugins (C:\Projects\Personal\personal\node_modules\electrode-server\lib\electrode-server.js:117:13)
From previous event:
    at startElectrodeServer (C:\Projects\Personal\personal\node_modules\electrode-server\lib\electrode-server.js:158:6)
    at Promise.try.then (C:\Projects\Personal\personal\node_modules\electrode-server\lib\electrode-server.js:218:16)
From previous event:
    at start (C:\Projects\Personal\personal\node_modules\electrode-server\lib\electrode-server.js:207:8)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)
From previous event:
    at electrodeServer (C:\Projects\Personal\personal\node_modules\electrode-server\lib\electrode-server.js:265:6)
    at startServer (C:/Projects/Personal/personal/src/server/index.js:12:31)
    at support.load.then (C:/Projects/Personal/personal/src/server/index.js:41:10)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)

    ESERVERSTART

    This error is thrown by the electrode-server module

    There was an error starting the Hapi.js server
    Please check the output of the stack trace below and correct the error shown

    If you have followed this resolution step and you are still seeing an
    error, please file an issue on the electrode-server repository

    https://github.com/electrode-io/electrode-server.git

    window is not defined

(node:22368) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: There was an error starting the Hapi.js server
```

**Comment by jshado1** [comment]
`window` being undefined is expected.

What @danialkhansari suggests will cause an exception as `import` cannot be used conditionally.

In our project, we created a simple helper to use in our code to determine when we should and shouldn't try to do browser things: `isSSR = typeof window === 'undefined'` and then we created a `browser` module that we import whenever we want to reference `window`:

```js
const browser = isSSR
  ? {
        window: {
            // stub only what you absolutely must access
        },
        document: {},
        language: 'en',
        location: { // you probably want to stub all of location's properties and methods
        },
    }
    : {
        window: window,
        document: window.document,
        // …
    };

// cookie mock
// Promise = bluebird

export default browser;
```
