### ISSUE TITLE
Big Hurdle When Getting Started: uncaughtException: only one instance of babel-polyfill is allowed 

### ISSUE THREAD

**Issue by eliecerthoms** [electrode-io/electrode#583]
## Type of issue
Bug

## My environment

* *OS version/details*: `Windows 10 64-bit`
* *Node version:* `8.0.0` 
* *npm version:* `5.4.2`
* *Version of yo :* `2.0.0`

## Expected behavior
I expected the server to run with no problems.

## Current behavior
The server crashes because there are two versions of `babel-polyfill`, on further investigation I saw that `babel-cli` includes that package, but it is also included in the root of `node_modules`... why? 

## Steps tried for solving problem

- When I delete the `babel-polyfill` in the root `node_modules` it leads to another error stating: `Error: Cannot find module 'babel-polyfill'` 

- Deleted `babel-cli` but the error persists. 

- Haven't tried deleting `babel-polyfill` from `babel-cli` mainly because I don't know how to. 

## Steps to reproduce the behavior
Follow the Getting Started Guide and get to the point of running `clap dev`

## Command line output
```
error: uncaughtException: only one instance of babel-polyfill is allowed                                                                                                
{ date: 'Tue Sep 26 2017 17:19:15 GMT-0500 (Hora est. Pacífico, Sudamérica)',                                                                                           
  process:                                                                                                                                                              
   { pid: 18704,                                                                                                                                                        
     uid: null,                                                                                                                                                         
     gid: null,                                                                                                                                                         
     cwd: 'C:\\Users\\edtho\\Desktop\\electrode\\started',                                                                                                              
     execPath: 'C:\\Program Files\\nodejs\\node.exe',                                                                                                                   
     version: 'v8.0.0',                                                                                                                                                 
     argv:                                                                                                                                                              
      [ 'node',                                                                                                                                                         
        'C:\\Users\\edtho\\Desktop\\electrode\\started\\src\\server\\index.js' ],                                                                                       
     memoryUsage:                                                                                                                                                       
      { rss: 90210304,                                                                                                                                                  
        heapTotal: 82124800,                                                                                                                                            
        heapUsed: 57815792,                                                                                                                                             
        external: 236635 } },                                                                                                                                           
  os: { loadavg: [ 0, 0, 0 ], uptime: 983177.3245022 },                                                                                                                 
  trace:                                                                                                                                                                
   [ { column: 9,                                                                                                                                                       
       file: 'C:\\Users\\edtho\\Desktop\\electrode\\started\\node_modules\\babel-polyfill\\lib\\index.js',                                                              
       function: null,                                                                                                                                                  
       line: 10,                                                                                                                                                        
       method: null,                                                                                                                                                    
       native: false },                                                                                                                                                 
     { column: 30,                                                                                                                                                      
       file: 'module.js',                                                                                                                                               
       function: 'Module._compile',                                                                                                                                     
       line: 569,                                                                                                                                                       
       method: '_compile',                                                                                                                                              
       native: false },                                                                                                                                                 
     { column: 10,                                                                                                                                                      
       file: 'module.js',                                                                                                                                               
       function: 'Module._extensions..js',                                                                                                                              
       line: 580,                                                                                                                                                       
       method: '.js',                                                                                                                                                   
       native: false },                                                                                                                                                 
     { column: 7,                                                                                                                                                       
       file: 'C:\\Users\\edtho\\AppData\\Roaming\\npm\\node_modules\\babel-cli\\node_modules\\babel-register\\lib\\node.js',                                            
       function: 'require.extensions.(anonymous function)',                                                                                                             
       line: 152,                                                                                                                                                       
       method: '(anonymous function)',                                                                                                                                  
       native: false },                                                                                                                                                 
     { column: 7,                                                                                                                                                       
       file: 'C:\\Users\\edtho\\Desktop\\electrode\\started\\node_modules\\babel-register\\lib\\node.js',                                                               
       function: 'Object.require.extensions.(anonymous function) [as .js]',                                                                                             
       line: 152,                                                                                                                                                       
       method: 'js]',                                                                                                                                                   
       native: false },                                                                                                                                                 
     { column: 32,                                                                                                                                                      
       file: 'module.js',                                                                                                                                               
       function: 'Module.load',                                                                                                                                         
       line: 503,                                                                                                                                                       
       method: 'load',                                                                                                                                                  
       native: false },                                                                                                                                                 
     { column: 12,                                                                                                                                                      
       file: 'module.js',                                                                                                                                               
       function: 'tryModuleLoad',                                                                                                                                       
       line: 466,                                                                                                                                                       
       method: null,                                                                                                                                                    
       native: false },                                                                                                                                                 
     { column: 3,                                                                                                                                                       
       file: 'module.js',                                                                                                                                               
       function: 'Module._load',                                                                                                                                        
       line: 458,                                                                                                                                                       
       method: '_load',                                                                                                                                                 
       native: false },                                                                                                                                                 
     { column: 17,                                                                                                                                                      
       file: 'module.js',                                                                                                                                               
       function: 'Module.require',                                                                                                                                      
       line: 513,                                                                                                                                                       
       method: 'require',                                                                                                                                               
       native: false },                                                                                                                                                 
     { column: 18,                                                                                                                                                      
       file: 'internal/module.js',                                                                                                                                      
       function: 'require',                                                                                                                                             
       line: 11,                                                                                                                                                        
       method: null,                                                                                                                                                    
       native: false } ],                                                                                                                                               
  stack:                                                                                                                                                                
   [ 'Error: only one instance of babel-polyfill is allowed',                                                                                                           
     '    at Object.<anonymous> (C:\\Users\\edtho\\Desktop\\electrode\\started\\node_modules\\babel-polyfill\\lib\\index.js:10:9)',                                     
     '    at Module._compile (module.js:569:30)',                                                                                                                       
     '    at Module._extensions..js (module.js:580:10)',                                                                                                                
     '    at require.extensions.(anonymous function) (C:\\Users\\edtho\\AppData\\Roaming\\npm\\node_modules\\babel-cli\\node_modules\\babel-register\\lib\\node.js:152:7
)',                                                                                                                                                                     
     '    at Object.require.extensions.(anonymous function) [as .js] (C:\\Users\\edtho\\Desktop\\electrode\\started\\node_modules\\babel-register\\lib\\node.js:152:7)',
     '    at Module.load (module.js:503:32)',                                                                                                                           
     '    at tryModuleLoad (module.js:466:12)',                                                                                                                         
     '    at Function.Module._load (module.js:458:3)',                                                                                                                  
     '    at Module.require (module.js:513:17)',                                                                                                                        
     '    at require (internal/module.js:11:18)' ] }                                                                                                                    
```

**Comment by qbitza** [comment]
I can confirm this issue.

**Comment by qbitza** [comment]
I downgraded from npm version 5.4.2 to npm version: 4.6.1 and everything is back to normal! It seems npm 5.4.x is buggy and it is recommended that you not use anything later than npm 5.3.0 until the issue has been resolved.
