### ISSUE TITLE
Server side unit tests not being transpiled

### ISSUE THREAD

**Issue by mcrowder65** [electrode-io/electrode#588]
This is a reopen of https://github.com/electrode-io/electrode/issues/38... Right now, if we want to test our server side code, we have to write it in es5, and then that means that if our server is sharing any code with the client, then we would have to write that in es5 too.

## Feature request:
Add transpiling to server

----

## My environment

* *OS: Mac os sierra
* *Node version: 6.11.2
* *npm version:3.10.10
* *Version of yo :2.0.0

## Expected behavior

Writing server side unit tests with es6 should be transpiled to es5 and still work.

## Current behavior

I can't write server side unit tests without writing my server in es5 and any shared code in es5..

## Steps to reproduce the behavior
Write a server side unit test in es6 like so... just using an import
```
"use strict";
import getUserInfo from "../../../src/server/auth";

describe("This test is here so npm test will pass", () => {

  it("test", () => {
    const two = 2;
    expect(two).eql(two);
  });
});
```

## Command line output
```
m-c02tr0mug8wl:po-neo-electrode m0c018p$ clap test-server-dev
[09:31:26] xclap version 0.2.13 at CWD/node_modules/xclap
[09:31:26] NodeJS version v6.11.2 at /Users/m0c018p/.nvm/versions/node/v6.11.2/bin/node
[09:31:26] CWD is /Users/m0c018p/po-neo-electrode
[09:31:27] Loaded CWD/xclap.js
[09:31:27] Added CWD/~/.bin to PATH
[09:31:27] Execute electrode/test-server-dev as function
/Users/m0c018p/po-neo-electrode/test/server/spec/temporary.spec.js:2
import getUserInfo from "../../../src/server/auth";
^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at /Users/m0c018p/po-neo-electrode/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (native)
    at Mocha.loadFiles (/Users/m0c018p/po-neo-electrode/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/Users/m0c018p/po-neo-electrode/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/Users/m0c018p/po-neo-electrode/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
[09:31:27] Failed Execute electrode/test-server-dev as function (864 ms)
 Execution Failed - Errors:
 1  shell cmd 'mocha -c --opts /Users/m0c018p/po-neo-electrode/node_modules/electrode-archetype-react-app-dev/config/mocha/mocha.opts test/server' exit code 1
```

**Comment by jchip** [comment]
I recommend to stick with require for now.  NodeJS 6 supports most of the other ES6 features.  8 supports even more.

**Comment by mcrowder65** [comment]
Created pull request to add transpiling to server side unit tests.  This is nice because if you use require then your code is not actually isomorphic since the browser can't use it..

https://github.com/electrode-io/electrode/pull/599
