### ISSUE TITLE
clap build-analyze throws error

### ISSUE THREAD

**Issue by mspoerer** [electrode-io/electrode#633]
Initial setup with `ignite generate-app`
Installed with HapiJS and PWA.

## Type of issue

Starting clap build-analyze throws the error (shown below).

## Expected behavior

Does not throw an error.

## Current behavior

Throws error: no such file or directory, open 'dist/js/bundle.*.js'

## Command line output

```
Error: ENOENT: no such file or directory, open 'dist/js/bundle.*.js'
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.<anonymous> (/Users/manuelsporer/Desktop/Workspace/gk/webc-app/node_modules/electrode-bundle-analyzer/lib/analyze-bundle.js:31:17)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
```

**Comment by mspoerer** [comment]
The name of the generated bundle in the optimize-stats task is hardcoded. It would be better if it would be configurable somehow.

**Comment by Evanlec** [comment]
seeing same issue
