### ISSUE TITLE
Failed loading module

### ISSUE THREAD

**Issue by boshun** [electrode-io/electrode#645]
Hi,
After I installed and ran npm start, I encounter the following issue. Could you help me solve it? Thanks.

    Failed loading module /var/www/electrode/node_modules/electrode-ota-server-dao-cassandra/lib/index.js: this is not a typed array.

    Unhandled rejection TypeError: Failed loading module /var/www/electrode/node_modules/electrode-ota-server-dao-cassandra/lib/index.js: this is not a typed array.
    at Object.from (native)
    at Object.<anonymous> (/var/www/electrode/node_modules/cassandra-driver/lib/encoder.js:12:23)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/electrode/node_modules/cassandra-driver/lib/connection.js:7:15)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/electrode/node_modules/cassandra-driver/lib/host-connection-pool.js:5:18)
    Unhandled rejection TypeError: Failed loading module /var/www/electrode/node_modules/electrode-ota-server-dao-cassandra/lib/index.js: this is not a typed array.
    at Object.from (native)
    at Object.<anonymous> (/var/www/electrode/node_modules/cassandra-driver/lib/encoder.js:12:23)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/electrode/node_modules/cassandra-driver/lib/connection.js:7:15)
    at Module._compile (module.1qaz2wsx at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/var/www/electrode/node_modules/cassandra-driver/lib/host-connection-pool.js:5:18)

my config/production.json is 

    {
	"plugins": {
		"electrode-ota-server-dao-cassandra": {
			"options": {
				"contactPoints": [
					"localhost"
				],
				"keyspace": "ota_db_1"
			}
		},
		"electrode-ota-server-fileservice": {
			"options": {
				"downloadUrl": "http://localhost:9001/storagev2/"
			}
		},
		"electrode-ota-server-auth": {
			"options": {
				"strategy": {
					"github-oauth": {
						"options": {
							"password": "xxxxxxx",
							"isSecure": true,
							"location": "xxx.xxx.xx.xxx",
							"clientId": "xxxxxxxxxxxxxxxxxxxxxxxxx",
							"clientSecret": "xxxxxxxxxxxxxxxxxxxxxxxxxx"
						}
					},
					"session": {
						"options": {
							"password": "xxxxxxxxxxxxxx",
							"isSecure": true
						}
					}

				}
			}
		}
	    }
    }

**Comment by didi0613** [comment]
@boshun  Please checkout here for ota server : https://github.com/electrode-io/electrode-ota-server :-)
