### ISSUE TITLE
Enzyme throwing error about getPublicInstance when mounting

### ISSUE THREAD

**Issue by ehguo** [electrode-io/electrode#654]
## Type of issue

Bug

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit` OSX
* *Node version:* `x.x.x` (run `node --version` in your terminal) 6.12.00
* *npm version:* `x.x.x` (run `npm --version` in your terminal) 3.10.10
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Expected behavior

Enzyme `mount` should mount correctly
## Current behavior

Throws error
## Steps to reproduce the behavior

```
it('should call loginFromStorage on mount', () => {
    const loginFromStorage = sinon.spy();
    component = mount(
      <ImageTagger
        {...props}
        loginFromStorage={loginFromStorage} />);
    expect(loginFromStorage.calledOnce).to.equal(true);
  });
```
## Command line output

```
TypeError: Cannot read property 'getPublicInstance' of undefined
    at WrapperComponent.getWrappedComponent (webpack:///Users/vn034pt/Walmart/image-tagger/node_modules/enzyme/build/ReactWrapperComponent.js:95:0 <- node_modules/electrode-archetype-react-app-dev/config/karma/entry.js:37233:32)
    at new ReactWrapper (webpack:///Users/vn034pt/Walmart/image-tagger/node_modules/enzyme/build/ReactWrapper.js:100:0 <- node_modules/electrode-archetype-react-app-dev/config/karma/entry.js:11338:34)
    at mount (webpack:///Users/vn034pt/Walmart/image-tagger/node_modules/enzyme/build/mount.js:19:0 <- node_modules/electrode-archetype-react-app-dev/config/karma/entry.js:60902:10)
    at Context.<anonymous> (webpack:///components/layouts/image-tagger.spec.js:35:6 <- node_modules/electrode-archetype-react-app-dev/config/karma/entry.js:84108:35)
```

## Notes

Most likely needs to be updated to v3

https://github.com/airbnb/enzyme/issues/1071

**Comment by ehguo** [comment]
Not sure what happened but it's fixed now...
