### ISSUE TITLE
`ignite generate-component` fails on dependency `@babel/traverse@7.0.0-beta.36`

### ISSUE THREAD

**Issue by s-bhupathiraju** [electrode-io/electrode#678]
## Type of issue

Cannot generate an electrode component repo using ignite menu

----

## My environment
Here is the output from `ignite check-nodejs`
[14:41:22] Electrode Ignite 2.0.0
[14:41:22] Running Check your NodeJS and npm environment
checking node and npm versions .. ◶
[14:41:22] You are using Node version 8.9.1. Electrode should work for you.
[14:41:22] You are using npm version 5.5.1. Electrode should work for you.
[14:41:22] Your Node binary path is: /usr/local/Cellar/node/8.9.1/bin/node

## Expected behavior
I wanted to generate an electrode component repo and get all the npm modules installed automatically.
## Current behavior
`ignite generate-component` ends up with an error

## Command line output

```
added 1668 packages in 76.546s
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: @babel/traverse@7.0.0-beta.36 (node_modules/babel-eslint/node_modules/@babel/traverse):
npm WARN 404 SKIPPING OPTIONAL DEPENDENCY: Not Found: @babel/traverse@7.0.0-beta.36

npm ERR! code E404
npm ERR! 404 Not Found: @babel/code-frame@7.0.0-beta.36

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/employee/.npm/_logs/2018-01-15T19_38_38_370Z-debug.log

Your new Electrode component is ready!
Your component is in wysiwyg-component/packages and your demo app is wysiwyg-component/demo-app

Type 'cd wysiwyg-component/demo-app' then 'clap dev' to run the development build for the demo app.

[14:38:38] Generator: electrode:component exited without any errors.
```

**Comment by didi0613** [comment]
Hi @s-bhupathiraju:

Thanks for reporting this issue.
I've just have a try on the same env you have. The error you provided above is not reproducible to me. 

Here is my `ignite check-nodejs`:
```
m-C02SL0GSG8WM:~ s0d00px$ ignite check-nodejs
[14:58:29] Electrode Ignite 2.0.0
[14:58:29] Running Check your NodeJS and npm environment
checking node and npm versions .. ◶
[14:58:30] You are using Node version 8.9.1. Electrode should work for you.
[14:58:30] You are using npm version 5.5.1. Electrode should work for you.
[14:58:30] Your Node binary path is: /Users/s0d00px/.nvm/versions/node/v8.9.1/bin/node
```

As I know, electrode component is not using `@babel/traverse@7.0.0-beta.36` or  `@babel/code-frame@7.0.0-beta.36`. Please have another try of`ignite generate-component` or providing mode details about this issue.
Thank you.

**Comment by s-bhupathiraju** [comment]
Thanks for responding Sheng. I tried again using yarn as a package manager and here is what is see now. `ignite generate-component` seem to be working fine. However when I do `clap dev` in demo-app, I see webpack bundle error with `babel`

## Terminal output:

```
| sbhupathiraju@lpmc-sanjayb:~/git/s-bhupathiraju$  => ignite generate-component
[23:23:43] Electrode Ignite 2.0.0
[23:23:43] Running Generate an Electrode component repo
[23:23:43] Loading generator electrode:component ...
Yeoman Electrode Component generator version 4.0.0
Loaded from /usr/local/lib/node_modules/electrode-ignite/node_modules/generator-electrode

Welcome to the Electrode Component Generator

We're going to set up a new Electrode component, ready for development with
react, webpack, demo, electrode component archetype, and live-reload
? What is your Package/GitHub project name? (e.g., 'wysiwyg-component') hello-world
? What is the ClassName for your component? HelloWorld
? What will be the npm package name? hello-world
? What will be the GitHub organization username (e.g., 'walmartlabs')?
? What is your name? (for copyright notice, etc.) s-bhupathiraju
? What is your GitHub Username? s-bhupathiraju
? Use double quotes or single quotes? "
? What is the name of the GitHub repo where this will be published? hello-world
? Would you like to create a new directory for your project? Yes
? Would you like to yarn install packages? Yes
   create ../.gitignore
   create ../package.json
   create ../README.md
   create ../lerna.json
   create ../packages/hello-world/.babelrc
   create ../packages/hello-world/.gitignore
   create ../packages/hello-world/.npmignore
   create ../packages/hello-world/.editorconfig
   create ../packages/hello-world/xclap.js
   create ../packages/hello-world/package.json
   create ../packages/hello-world/README.md
   create ../packages/hello-world/src/components/hello-world.jsx
   create ../packages/hello-world/src/components/accordion.jsx
   create ../packages/hello-world/src/styles/hello-world.css
   create ../packages/hello-world/src/styles/accordion.css
   create ../packages/hello-world/demo/examples/hello-world.example
   create ../packages/hello-world/demo/demo.css
   create ../packages/hello-world/demo/demo.jsx
   create ../packages/hello-world/components.md
   create ../packages/hello-world/src/lang/default-messages.js
   create ../packages/hello-world/src/lang/en.json
   create ../packages/hello-world/src/lang/tenants/electrodeio/default-messages.js
   create ../packages/hello-world/src/index.js
   create ../packages/hello-world/test/client/.eslintrc
   create ../packages/hello-world/test/client/components/hello-world.spec.jsx
   create ../packages/hello-world/test/client/components/helpers/intl-enzyme-test-helper.js
   create package.json
   create archetype/config/index.js
   create archetype/config/webpack/component-alias.config.js
   create archetype/config/webpack/webpack.config.dev.js
   create archetype/config/webpack/webpack.config.js
   create src/client/components/home.jsx
   create src/client/reducers/index.jsx
   create src/client/actions/index.jsx
   create README.md
   create config/default.js
   create .editorconfig
   create xclap.js
   create config/development.json
   create config/production.js
   create config/production.json
   create test/client/.babelrc
   create test/client/.eslintrc.js
   create test/client/components/home.spec.jsx
   create test/server/.babelrc
   create test/server/.eslintrc.js
   create test/server/server.spec.js
   create .eslintrc.js
   create src/server/.babelrc
   create src/server/.eslintrc.js
   create src/server/index.js
   create src/client/.babelrc
   create src/client/.eslintrc.js
   create src/client/app.jsx
   create src/client/routes.jsx
   create src/client/styles/custom.css
   create src/client/styles/normalize.css
   create src/client/styles/raleway.css
   create src/client/styles/skeleton.css
   create src/client/images/electrode.png
   create .travis.yml
   create LICENSE
   create config/sw-config.js
   create src/server/views/index-view.jsx
   create src/server/plugins/pwa.js
Initialized empty Git repository in /Users/employee/git/s-bhupathiraju/hello-world/.git/
yarn install v1.3.2
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 📃  Building fresh packages...
success Saved lockfile.
✨  Done in 20.04s.
yarn install v1.3.2
warning package.json: No license field
info No lockfile found.
warning hello-world@0.0.1: No license field
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning electrode-archetype-react-component-dev > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning electrode-archetype-react-component-dev > component-playground > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning electrode-archetype-react-component-dev > karma-mocha-reporter > karma > log4js > nodemailer@2.7.2: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
warning electrode-archetype-react-component-dev > karma-mocha-reporter > karma > log4js > loggly > request > node-uuid@1.4.8: Use uuid module instead
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning "electrode-archetype-react-component-dev > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
[5/5] 📃  Building fresh packages...
success Saved lockfile.
$ clap prepublish
[23:28:00] xclap version 0.2.19 at CWD/node_modules/xclap
[23:28:00] NodeJS version v8.9.1 at /usr/local/Cellar/node/8.9.1/bin/node
[23:28:00] CWD is /Users/employee/git/s-bhupathiraju/hello-world/packages/hello-world
[23:28:00] Loaded CWD/xclap.js
[23:28:00] Added CWD/~/.bin to PATH
[23:28:00] Process ext/prepublish serial array ["npm:prepublish"]
[23:28:00] -Process electrode/npm:prepublish serial array ["build-lib","build-dist-min"]
[23:28:00] ..Process build-lib's dependency serial array ["~production-env"]
[23:28:00] ---Execute electrode/~production-env as function
[23:28:00] >>>Done Execute electrode/~production-env as function (0 ms)
[23:28:00] >>Done Process build-lib's dependency serial array ["~production-env"] (1 ms)
[23:28:00] ..Process electrode/build-lib serial array ["clean-lib","babel-src-step","build-lib:flatten-l10n","build-lib:copy-flow","build-lib:clean-tmp"]
[23:28:00] ---Execute electrode/clean-lib as function
[23:28:00] >>>Done Execute electrode/clean-lib as function (3 ms)
[23:28:00] ...Execute electrode/babel-src-step babel -D src -d lib
src/components/accordion.jsx -> lib/components/accordion.js
src/components/hello-world.jsx -> lib/components/hello-world.js
src/index.js -> lib/index.js
src/lang/default-messages.js -> lib/lang/default-messages.js
src/lang/tenants/electrodeio/default-messages.js -> lib/lang/tenants/electrodeio/default-messages.js
[23:28:03] >>>Done Execute electrode/babel-src-step babel -D src -d lib (2.34 sec)
[23:28:03] ---Execute electrode/build-lib:flatten-l10n node CWD/~/electrode-archetype-react-component-dev/scripts/l10n/flatten-messages.js
[23:28:03] >>>Done Execute electrode/build-lib:flatten-l10n node CWD/~/electrode-archetype-react-component-dev/scripts/l10n/flatten-messages.js (500 ms)
[23:28:03] ...Execute electrode/build-lib:copy-flow node CWD/~/electrode-archetype-react-component-dev/scripts/copy-as-flow-declaration.js
[23:28:03] >>>Done Execute electrode/build-lib:copy-flow node CWD/~/electrode-archetype-react-component-dev/scripts/copy-as-flow-declaration.js (93 ms)
[23:28:03] ---Execute electrode/build-lib:clean-tmp as function
[23:28:03] >>>Done Execute electrode/build-lib:clean-tmp as function (16 ms)
[23:28:03] >>Done Process electrode/build-lib serial array ["clean-lib","babel-src-step","build-lib:flatten-l10n","build-lib:copy-flow","build-lib:clean-tmp"] (2.95 sec)
[23:28:03] ..Process build-dist-min's dependency serial array ["~production-env"]
[23:28:03] ---Execute electrode/~production-env as function
[23:28:03] >>>Done Execute electrode/~production-env as function (0 ms)
[23:28:03] >>Done Process build-dist-min's dependency serial array ["~production-env"] (0 ms)
[23:28:03] ..Execute electrode/build-dist-min webpack --config CWD/~/electrode-archetype-react-component-dev/config/webpack/webpack.config.js --colors
Hash: caa9cc71afafd10b09a0
Version: webpack 3.10.0
Time: 4277ms
            Asset     Size  Chunks             Chunk Names
    bundle.min.js  46.6 kB       0  [emitted]  main
bundle.min.js.map   455 kB       0  [emitted]  main
  [59] ./src/index.js 350 bytes {0} [built]
 [113] ./src/styles/hello-world.css 1.08 kB {0} [built]
 [114] ./node_modules/css-loader?modules!./node_modules/postcss-loader!./src/styles/hello-world.css 570 bytes {0} [built]
 [116] ./src/styles/accordion.css 1.08 kB {0} [built]
 [117] ./node_modules/css-loader?modules!./node_modules/postcss-loader!./src/styles/accordion.css 967 bytes {0} [built]
    + 113 hidden modules
[23:28:10] >>Done Execute electrode/build-dist-min webpack --config CWD/~/electrode-archetype-react-component-dev/config/webpack/webpack.config.js --colors (6.88 sec)
[23:28:10] >Done Process electrode/npm:prepublish serial array ["build-lib","build-dist-min"] (9.84 sec)
[23:28:10] Done Process ext/prepublish serial array ["npm:prepublish"] (9.84 sec)
✨  Done in 201.66s.
yarn install v1.3.2
info No lockfile found.
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...
[4/5] 🔗  Linking dependencies...
warning " > electrode-redux-router-engine@1.5.0" has unmet peer dependency "react@^16.0.0 || ^15.3.1 || ^0.14.8".
warning " > electrode-redux-router-engine@1.5.0" has unmet peer dependency "react-dom@^16.0.0 || ^15.3.1 || ^0.14.8".
warning "electrode-redux-router-engine > react-redux@5.0.6" has unmet peer dependency "react@^0.14.0 || ^15.0.0-0 || ^16.0.0-0".
warning "electrode-redux-router-engine > react-router@3.2.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0-rc".
warning "electrode-archetype-react-app-dev > enzyme-adapter-react-16@1.1.1" has unmet peer dependency "react@^16.0.0-0".
warning "electrode-archetype-react-app-dev > enzyme-adapter-react-16@1.1.1" has unmet peer dependency "react-dom@^16.0.0-0".
warning "electrode-archetype-react-app-dev > postcss-cssnext@2.11.0" has unmet peer dependency "caniuse-db@^1.0.30000652".
warning "electrode-archetype-react-app-dev > react-intl@2.4.0" has unmet peer dependency "react@^0.14.9 || ^15.0.0 || ^16.0.0".
warning "electrode-archetype-react-app-dev > react-intl@2.4.0" has unmet peer dependency "prop-types@^15.5.4".
warning "electrode-archetype-react-app-dev > react-test-renderer@16.2.0" has unmet peer dependency "react@^16.0.0".
warning "electrode-archetype-react-app-dev > enzyme-adapter-react-16 > enzyme-adapter-utils@1.3.0" has unmet peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "electrode-archetype-react-app-dev > enzyme-adapter-react-16 > react-reconciler@0.7.0" has unmet peer dependency "react@^16.0.0".
warning "electrode-archetype-react-app-dev > electrode-electrify > bl@0.7.0" has unmet peer dependency "stream-browserify@*".
warning "electrode-archetype-react-app-dev > react-hot-loader > react-hot-api@0.4.7" has unmet peer dependency "react@>=0.11.0 || ^0.14.0-rc".
[5/5] 📃  Building fresh packages...
[1/6] ⢀ electrode-archetype-opt-inferno
[-/6] ⢀ waiting...
[3/6] ⢀ fsevents
success Saved lockfile.
✨  Done in 615.75s.

Your new Electrode component is ready!
Your component is in hello-world/packages and your demo app is hello-world/demo-app

Type 'cd hello-world/demo-app' then 'clap dev' to run the development build for the demo app.

[23:38:27] Generator: electrode:component exited without any errors.
________________________________________________________________________________
| sbhupathiraju@lpmc-sanjayb:~/git/s-bhupathiraju$  => ls
hello-world           platform.training.tdd wysiwyg-component
________________________________________________________________________________
| sbhupathiraju@lpmc-sanjayb:~/git/s-bhupathiraju$  => cd hello-world/
✔ ~/git/s-bhupathiraju/hello-world [master L|…69]
09:05 $ ll
total 84
drwxr-xr-x    5 sbhupathiraju  staff    170 Jan 15 23:24 ..
drwxr-xr-x    3 sbhupathiraju  staff    102 Jan 15 23:24 packages
-rw-r--r--    1 sbhupathiraju  staff    656 Jan 15 23:24 package.json
-rw-r--r--    1 sbhupathiraju  staff     88 Jan 15 23:24 lerna.json
-rw-r--r--    1 sbhupathiraju  staff   1208 Jan 15 23:24 README.md
-rw-r--r--    1 sbhupathiraju  staff   8066 Jan 15 23:24 .gitignore
drwxr-xr-x    9 sbhupathiraju  staff    306 Jan 15 23:24 .git
-rw-r--r--    1 sbhupathiraju  staff  63517 Jan 15 23:24 yarn.lock
drwxr-xr-x  270 sbhupathiraju  staff   9180 Jan 15 23:24 node_modules
drwxr-xr-x   11 sbhupathiraju  staff    374 Jan 15 23:24 .
drwxr-xr-x   16 sbhupathiraju  staff    544 Jan 15 23:38 demo-app
✔ ~/git/s-bhupathiraju/hello-world [master L|…69]
09:05 $ cd demo-app/
✔ ~/git/s-bhupathiraju/hello-world/demo-app [master L|…69]
09:05 $ clap dev
[09:05:47] xclap version 0.2.19 at CWD/node_modules/xclap
[09:05:47] NodeJS version v8.9.1 at /usr/local/Cellar/node/8.9.1/bin/node
[09:05:47] CWD is /Users/employee/git/s-bhupathiraju/hello-world/demo-app
[09:05:48] Loaded CWD/xclap.js
[09:05:48] Added CWD/~/.bin to PATH
[09:05:48] Process dev's dependency serial array [".remove-log-files",".development-env",".clean.build",".mk-dist-dir"]
[09:05:48] -Execute electrode/.remove-log-files as function
[09:05:48] >Done Execute electrode/.remove-log-files as function (0 ms)
[09:05:48] .Execute electrode/.development-env as function
[09:05:48] >Done Execute electrode/.development-env as function (0 ms)
[09:05:48] -Process electrode/.clean.build serial array [".clean.dist",".clean.dll"]
[09:05:48] ..Execute electrode/.clean.dist as function
[09:05:48] >>Done Execute electrode/.clean.dist as function (2 ms)
[09:05:48] --Execute electrode/.clean.dll as function
[09:05:48] >>Done Execute electrode/.clean.dll as function (0 ms)
[09:05:48] >Done Process electrode/.clean.build serial array [".clean.dist",".clean.dll"] (4 ms)
[09:05:48] .Execute electrode/.mk-dist-dir as function
[09:05:48] >Done Execute electrode/.mk-dist-dir as function (1 ms)
[09:05:48] Done Process dev's dependency serial array [".remove-log-files",".development-env",".clean.build",".mk-dist-dir"] (8 ms)
[09:05:48] Process electrode/dev serial array [".webpack-dev",["wds.dev","server-watch","generate-service-worker"]]
[09:05:48] .Execute electrode/.webpack-dev as function
[09:05:48] >Done Execute electrode/.webpack-dev as function (0 ms)
[09:05:48] -Process electrode/dev.S concurrent array ["wds.dev","server-watch","generate-service-worker"]
[09:05:48] ..Execute electrode/wds.dev webpack-dev-server --config CWD/~/electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js --progress --colors --port 2992 --host localhost
[09:05:48] --Execute electrode/generate-service-worker as function
[09:05:48] ..Process server-watch's dependency serial array [".init-bundle.valid.log"]
[09:05:48] >>Done Execute electrode/generate-service-worker as function (1 ms)
[09:05:48] ---Execute electrode/.init-bundle.valid.log as function
[09:05:48] >>>Done Execute electrode/.init-bundle.valid.log as function (1 ms)
[09:05:48] >>Done Process server-watch's dependency serial array [".init-bundle.valid.log"] (1 ms)
[09:05:48] ..Execute electrode/server-watch as function
[nodemon] 1.14.11
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /Users/employee/git/s-bhupathiraju/hello-world/demo-app/src/server/**/* /Users/employee/git/s-bhupathiraju/hello-world/demo-app/config/**/*
info: Custom webpack config webpack.config.dev.js loaded from CWD/archetype/config/webpack
info: Entry point configuration /Users/employee/git/s-bhupathiraju/hello-world/demo-app/src/client/entry.config.js is not found, using default entry point...
Just FYI: optional module not found; Path "/Users/employee/git/s-bhupathiraju/hello-world/demo-app/config/default.json"
info: PWA enabled with config from /Users/employee/git/s-bhupathiraju/hello-world/demo-app/config/sw-config.js
info: Not disabling NodeSourcePlugin.  NODE_ENV: 'development'
 10% building modules 1/1 modules 0 active
Project is running at http://localhost:2992/
webpack output is served from http://localhost:2992/js/
 27% building modules 147/170 modules 23 active .../lib/transport/lib/sender-receiver.js{ Error: Cannot find module 'babel-preset-es2015'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.requireRelative.resolve (/Users/employee/git/s-bhupathiraju/hello-world/packages/hello-world/node_modules/require-relative/index.js:30:17)
    at module.exports (/Users/employee/git/s-bhupathiraju/hello-world/packages/hello-world/node_modules/modify-babel-preset/index.js:25:23)
    at Object.<anonymous> (/Users/employee/git/s-bhupathiraju/hello-world/packages/hello-world/node_modules/babel-preset-es2015-loose/index.js:5:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17) code: 'MODULE_NOT_FOUND' }
webpack bundle is now VALID but has ERRORS
webpack report is served from http://localhost:2992/reporter
```

**Comment by didi0613** [comment]
@s-bhupathiraju thank you for your detailed info.
Can you please upgrade your electrode-ignite to the latest: @2.0.2, there are few fixes included in the latest releases. Please let me know if it is working
Thanks!

**Comment by princeasokan** [comment]
I got the above same error, then i just  run command also ,getting the following error too.

prince@princemlU304:/media/prince/New Volume/tutorial/tutorial_project/test/myapp$ clap dev
[13:11:18] xclap version 0.2.21 at CWD/node_modules/xclap
[13:11:18] NodeJS version v9.4.0 at /usr/local/bin/node
[13:11:18] CWD is /media/prince/New Volume/tutorial/tutorial_project/test/myapp
[13:11:18] Loaded CWD/xclap.js
[13:11:18] Added CWD/~/.bin to PATH
[13:11:18] Process dev's dependency serial array [".remove-log-files",".development-env",".clean.build",".mk-dist-dir"]
[13:11:18] -Execute electrode/.remove-log-files as function
[13:11:18] >Done Execute electrode/.remove-log-files as function (2 ms)
[13:11:18] .Execute electrode/.development-env as function
[13:11:18] >Done Execute electrode/.development-env as function (0 ms)
[13:11:18] -Process electrode/.clean.build serial array [".clean.dist",".clean.dll"]
[13:11:18] ..Execute electrode/.clean.dist as function
[13:11:18] >>Done Execute electrode/.clean.dist as function (10 ms)
[13:11:18] --Execute electrode/.clean.dll as function
[13:11:18] >>Done Execute electrode/.clean.dll as function (1 ms)
[13:11:18] >Done Process electrode/.clean.build serial array [".clean.dist",".clean.dll"] (12 ms)
[13:11:18] .Execute electrode/.mk-dist-dir as function
[13:11:18] >Done Execute electrode/.mk-dist-dir as function (2 ms)
[13:11:18] Done Process dev's dependency serial array [".remove-log-files",".development-env",".clean.build",".mk-dist-dir"] (19 ms)
[13:11:18] Process electrode/dev serial array [".webpack-dev",["wds.dev","server-watch","generate-service-worker"]]
[13:11:18] .Execute electrode/.webpack-dev as function
[13:11:18] >Done Execute electrode/.webpack-dev as function (1 ms)
[13:11:18] -Process electrode/dev.S concurrent array ["wds.dev","server-watch","generate-service-worker"]
[13:11:18] ..Execute electrode/wds.dev webpack-dev-server --watch --watch-aggregate-timeout 2000 --config CWD/~/electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js --progress --colors --port 2992 --host localhost
[13:11:18] --Execute electrode/generate-service-worker as function
[13:11:18] ..Process server-watch's dependency serial array [".init-bundle.valid.log"]
[13:11:18] >>Done Execute electrode/generate-service-worker as function (1 ms)
[13:11:18] ---Execute electrode/.init-bundle.valid.log as function
[13:11:18] >>>Done Execute electrode/.init-bundle.valid.log as function (17 ms)
[13:11:18] >>Done Process server-watch's dependency serial array [".init-bundle.valid.log"] (19 ms)
[13:11:18] ..Execute electrode/server-watch as function
[nodemon] 1.17.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: .etmp/bundle.valid.log /media/prince/New Volume/tutorial/tutorial_project/test/myapp/src/server/**/* /media/prince/New Volume/tutorial/tutorial_project/test/myapp/config/**/*
info: APP_SRC_DIR set to src/
module.js:557
    throw err;
    ^

Error: Cannot find module '/media/prince/New'
    at Function.Module._resolveFilename (module.js:555:15)
    at Function.Module._load (module.js:482:25)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at requireConfig (/media/prince/New Volume/tutorial/tutorial_project/test/myapp/node_modules/webpack/bin/convert-argv.js:97:18)
    at /media/prince/New Volume/tutorial/tutorial_project/test/myapp/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/media/prince/New Volume/tutorial/tutorial_project/test/myapp/node_modules/webpack/bin/convert-argv.js:102:15)
    at Object.<anonymous> (/media/prince/New Volume/tutorial/tutorial_project/test/myapp/node_modules/webpack-dev-server/bin/webpack-dev-server.js:223:50)
    at Module._compile (module.js:660:30)
[13:11:21] >>Failed Execute electrode/wds.dev webpack-dev-server --watch --watch-aggregate-timeout 2000 --config CWD/~/electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js --progress --colors --port 2992 --host localhost (3.10 sec)
[13:11:21] >>Done Execute electrode/server-watch as function (3.07 sec)
[13:11:21] >Done Process electrode/dev.S concurrent array ["wds.dev","server-watch","generate-service-worker"] (3.11 sec)
[13:11:21] Done Process electrode/dev serial array [".webpack-dev",["wds.dev","server-watch","generate-service-worker"]] (3.11 sec)
 Execution Failed - Errors: 
 1  shell cmd 'webpack-dev-server --watch --watch-aggregate-timeout 2000 --config /media/prince/New Volume/tutorial/tutorial_project/test/myapp/node_modules/electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js --progress --colors --port 2992 --host localhost' exit code 1

**Comment by jchip** [comment]
@princeasokan please do not name your files or directories with spaces:

`/media/prince/New Volume/tutorial/tutorial_project/test/myapp`

"New` `Volume"

**Comment by didi0613** [comment]
@princeasokan @s-bhupathiraju Hi, does removing the spaces from your files/directories resolves the problem?
