### ISSUE TITLE
Clap dev fails on electrode app from ignite

### ISSUE THREAD

**Issue by ajbowler** [electrode-io/electrode#726]
## Type of issue

Bug

----

## My environment

Windows 7 64bit
* *Node version: `8.9.4`
* *npm version:* `5.6.0`
* *Version of yo :* 2.0

## Expected behavior

The app should start.

## Current behavior

The app fails on start.

## Steps to reproduce the behavior

Be on Windows OS, any version 7+ should suffice as the nodemon code just checks for Windows.
Create new Electrode app with ignite ("Generate an Electrode application")
Run `clap dev`

## Command line output

Gist: https://gist.github.com/ajbowler/57b6e7edec13a0144beb5d3aa51b9a4d

Main error:

```
 Execution Failed - Errors:
 1  shell cmd 'nodemon --delay 1 -C --ext js,jsx,json,yaml --watch .etmp\bundle.valid.log --watch src\server --watch config --exec node C:\Users\abowler\code\test-my-sanity\test-my-sanity\node_modules\electrode-archetype-react-app/support/babel-run src\server' exit code 1
    at error (C:\Users\abowler\code\test-my-sanity\test-my-sanity\node_modules\xsh\lib\exec.js:9:17)
    at shell.exec (C:\Users\abowler\code\test-my-sanity\test-my-sanity\node_modules\xsh\lib\exec.js:49:39)
    at C:\Users\abowler\code\test-my-sanity\test-my-sanity\node_modules\shcmd\src\exec.js:204:9
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
```

Nodemon was also recently published with 1.15.0 and is pulled in by Electrode. Suggested fix is to bump the nodemon version back down to 1.14.12.

**Comment by ajbowler** [comment]
Issue appears to be fixed with latest nodemon (1.17.17)
