### ISSUE TITLE
Remove karma-sonarqube-unit-reporter dependency in react-app-dev archetype

### ISSUE THREAD

**Issue by jshado1** [electrode-io/electrode#751]
## Type of issue

Bug

Technically not a bug in Electrode, but it is caused by Electrode's dependency that we can't remove ourselves.

`karma-sonarqube-unit-reporter` is looking for [an exact match of `'describe('`](https://github.com/tornaia/karma-sonarqube-unit-reporter/blob/master/src/file-util.js#L18), despite mocha's API containing other patterns.

The maintainers have not addressed or even responded to tornaia/karma-sonarqube-unit-reporter#23, originally reported to them 5 months ago (the exact line with the bug was provided to them 4 months ago).

----

## My environment

* *OS version/details*: `OSX 10.11.6`
* *Node version:* `6.13.1`
* *npm version:* `3.10.10`
* *Version of yo :* N/A

## Expected behavior

No error

## Current behavior

Entire spec suit run breaks.

## Steps to reproduce the behavior

1. In any client spec file, add `.only` between `describe` and `(` → `describe.only(`
1. Run `clap test-frontend`
1. 💥

## Command line output

```
16 03 2018 00:54:04.732:ERROR [karma]: Error: Missing attribute value for attribute path of element file

    at new XMLAttribute (/Users/[…]/[PROJECT_PATH]/node_modules/xmlbuilder/lib/XMLAttribute.js:14:15)
    at XMLElement.module.exports.XMLElement.attribute (/Users/[…]/[PROJECT_PATH]/node_modules/xmlbuilder/lib/XMLElement.js:83:35)
    at XMLElement.module.exports.XMLElement.attribute (/Users/[…]/[PROJECT_PATH]/node_modules/xmlbuilder/lib/XMLElement.js:76:16)
    at new XMLElement (/Users/[…]/[PROJECT_PATH]/node_modules/xmlbuilder/lib/XMLElement.js:34:14)
    at XMLElement.module.exports.XMLNode.node (/Users/[…]/[PROJECT_PATH]/node_modules/xmlbuilder/lib/XMLNode.js:160:15)
    at XMLElement.module.exports.XMLNode.element (/Users/[…]/[PROJECT_PATH]/node_modules/xmlbuilder/lib/XMLNode.js:105:28)
    at XMLElement.module.exports.XMLNode.ele (/Users/[…]/[PROJECT_PATH]/node_modules/xmlbuilder/lib/XMLNode.js:273:19)
    at SonarQubeUnitReporter.specSuccess.specSkipped.specFailure (/Users/[…]/[PROJECT_PATH]/node_modules/karma-sonarqube-unit-reporter/index.js:148:26)
    at SonarQubeUnitReporter.BaseReporter.onSpecComplete (/Users/[…]/[PROJECT_PATH]/node_modules/karma/lib/reporters/base.js:89:12)
    at Server.<anonymous> (/Users/[…]/[PROJECT_PATH]/node_modules/karma/lib/events.js:13:22)
    at emitTwo (events.js:111:20)
    at Server.emit (events.js:191:7)
    at Browser.onResult (/Users/[…]/[PROJECT_PATH]/node_modules/karma/lib/browser.js:224:13)
    at Socket.<anonymous> (/Users/[…]/[PROJECT_PATH]/node_modules/karma/lib/events.js:13:22)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
```

**Comment by jshado1** [comment]
Meantime, this can be removed downstream by adding the following to a project's `/archetypes/config/karma/karma.conf.js`

```js
_.pull(settings.plugins, 'karma-sonarqube-unit-reporter');
_.pull(settings.reporters, 'sonarqubeUnit');
delete settings.sonarQubeUnitReporter;
```
