### ISSUE TITLE
Windows Setup

### ISSUE THREAD

**Issue by TerrySlack** [electrode-io/electrode#754]
## Type of issue

Bug
----

## My environment

* *Windows 10 64-bit`
* *Node version:* `9.8.0`
* *npm version:* `5.7.1`
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)

## Expected behavior

Project should startup up, running clap dev

## Current behavior
Hi all, trying out Electrode for the first time, on Windows 10. So far, a few roadblocks, but have gotten to the point of creating an app and then running clap dev. I run into an issue where an error is throw. Specifically "Cannot find moduel C:\Node". I installed cross-env, and used it in my script in my package.json file. However, no luck. Does anyone have any suggestions? And yes, Node is installed, working fine in other projects. Only have this issue using clap to start a project

## Steps to reproduce the behavior
Follow the steps in the tutorial to create an app and then get it running

## Command line output

```
Paste your error output over here
Error: Cannot find module 'C:\Node'
at Function.Module._resolveFilename (module.js:543:15)
at Function.Module._load (module.js:470:25)
at Module.require (module.js:593:17)
at require (internal/module.js:11:18)
at requireConfig (C:\Node Projects\Apps with Electrode\electrode-app\node_modules\webpack\bin\convert-argv.js:97:18)
at C:\Node Projects\Apps with Electrode\electrode-app\node_modules\webpack\bin\convert-argv.js:104:17
at Array.forEach (<anonymous>)
at module.exports (C:\Node Projects\Apps with Electrode\electrode-app\node_modules\webpack\bin\convert-argv.js:102:15)
at Object.<anonymous> (C:\Node Projects\Apps with Electrode\electrode-app\node_modules\webpack-dev-server\bin\webpack-dev-server.js:223:50)
at Module._compile (module.js:649:30)
[10:44:29] >>Failed Execute electrode/wds.dev webpack-dev-server --watch --watch-aggregate-timeout 2000 --config CWD~\electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js --progress --colors --port 2992 --host localhost (1.33 sec)
[10:44:29] >>Done Execute electrode/server-watch as function (1.36 sec)
[10:44:29] >Done Process electrode/dev.S concurrent array ["wds.dev","server-watch","generate-service-worker"] (1.37 sec)
[10:44:29] Done Process electrode/dev serial array [".webpack-dev",["wds.dev","server-watch","generate-service-worker"]] (1.37 sec)
Execution Failed - Errors:
1 shell cmd 'webpack-dev-server --watch --watch-aggregate-timeout 2000 --config C:\Node Projects\Apps with Electrode\electrode-app\node_modules\electrode-archetype-react-app-dev/config/webpack/webpack.config.dev.js --progress --colors --port 2992 --host localhost' exit code 1
at error (C:\Node Projects\Apps with Electrode\electrode-app\node_modules\xsh\lib\exec.js:9:17)
at shell.exec (C:\Node Projects\Apps with Electrode\electrode-app\node_modules\xsh\lib\exec.js:49:39)
at C:\Node Projects\Apps with Electrode\electrode-app\node_modules\shcmd\src\exec.js:204:9
at ChildProcess.exithandler (child_process.js:280:5)
at ChildProcess.emit (events.js:180:13)
at maybeClose (internal/child_process.js:936:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)

**Comment by datvong-wm** [comment]
Try it without any spaces in the directory path.  In your case "Node Projects"

**Comment by TerrySlack** [comment]
If I try it without spaces, it will not work, as you can use spaces, in a filepath in windows.
Are there any docs on getting this to run in Windows?

**Comment by datvong-wm** [comment]
Here is a good starting point.  https://docs.electrode.io/chapter1/quick-start/start-with-app.html
It should work the same for Windows, with that caveat about the spaces.

**Comment by TerrySlack** [comment]
Looks like we are going in circles.  This is what I started out with, and was working on creating an electrode app, as per the docs.  However, I did go in and remove the spaces as you suggested and it worked.  Still, I think it would be really helpful to have a doc up, that is easy to find, outlining what you need to do to get things working on windows.  I'm curious though, I run many projects out of the folder "Node Projects" with a space.  And no issues.  Why is it an issue with electrode?

**Comment by jchip** [comment]
There are a few reasons:

A significant part of Electrode is about using build tools to create your app for you and that means command lines.  With spaces in your file names, which would have to be quoted in commands lines, and we were just not used to that, because:

Most of us are using Unix.  In fact, we primarily developed Electrode for Unix and Windows was an after thought after we open sourced it.  Of course spaces in file names are supported in Unix but we are not used to it and we don't particularly watch out for it.

Most of us are conditioned to avoid spaces in identifiers.  The first rule of programming is spaces are not allowed in identifiers.  Plus as we use command line a lot, so the addition of spaces in paths makes it just inconvenient.

**Comment by jchip** [comment]
just released a few fixes for windows

**Comment by TerrySlack** [comment]
You're description describes your team and not external devs, yet you released what looks like a fantastic product, to external devs.  So where is the focus.  On keeping your internal dev experience to your liking, or simply making your product work for all of us?

**Comment by TerrySlack** [comment]
Joel,
Meant to add, one thing that seemed to get me as far as doing a build, or at least getting past the first batch of errors, was to add cross-env and use it in my package.json, in the scripts commands.  It's a package that helps with script execution in windows.  I know adding another dependency is not a good thing, but perhaps it could help mitigate issues in Electrode, in windows.
