### ISSUE TITLE
Generated Electrode app with Koa throws an error on first start

### ISSUE THREAD

**Issue by sergesemashko** [electrode-io/electrode#889]
## Type of issue

Bug

----

## My environment

* *OS version/details*: `eg. Windows 10 64-bit`
Mac OS Sierra
* *Node version:* `x.x.x` (run `node --version` in your terminal)
Node v8.9.4
* *npm version:* `x.x.x` (run `npm --version` in your terminal)
NPM v5.7.1
* *Version of yo :* `x.x.x` (run `yo --version` in your terminal)
YO v2.0.4

## Expected behavior

After the app is generated by `ignite generate-app` and using 'Koa' `npm start` should show demo app.

## Current behavior

Electrode app throws an error while starting:
```
TypeError: router is not a function
    at _.each.method (/Users/siarhei206492423/Sites/test/electrode-4/node_modules/electrode-react-webapp/lib/koa/index.js:70:7)
    at arrayEach (/Users/siarhei206492423/Sites/test/electrode-4/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/siarhei206492423/Sites/test/electrode-4/node_modules/lodash/lodash.js:9342:14)
    at _.each (/Users/siarhei206492423/Sites/test/electrode-4/node_modules/electrode-react-webapp/lib/koa/index.js:64:7)
    at /Sites/test/electrode-4/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/Sites/test/electrode-4/node_modules/lodash/lodash.js:3010:24)
    at /Sites/test/electrode-4/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/Sites/test/electrode-4/node_modules/lodash/lodash.js:9342:14)
    at registerRoutes (/Sites/test/electrode-4/node_modules/electrode-react-webapp/lib/koa/index.js:42:5)
    at Promise (/Sites/test/electrode-4/src/server/koa-server.js:37:12)
    at setRouteHandler (/Sites/test/electrode-4/src/server/koa-server.js:34:3)
From previous event:
    at electrodeServer (/Sites/test/electrode-4/src/server/koa-server.js:64:6)
    at startServer (/Sites/test/electrode-4/src/server/index.js:16:10)
    at support.load.then (/Sites/test/electrode-4/src/server/index.js:23:12)
    at <anonymous>
[nodemon] clean exit - waiting for changes before restart
```

## Steps to reproduce the behavior

1. Install the app using `ignite generate-app`
1. Pick "Koa"
1. Run `npm start`

## Command line output
```
$ npm start

> electrode-4@0.0.1 start /Sites/test/electrode-4
> if test "$NODE_ENV" = "production"; then npm run prod-start; else clap dev; fi

[17:43:14] xclap version 0.2.21 at CWD/node_modules/xclap
[17:43:14] NodeJS version v8.9.4 at /usr/local/bin/node
[17:43:15] CWD is /Sites/test/electrode-4
[17:43:15] Loaded CWD/xclap.js
[17:43:15] Added CWD/~/.bin to PATH
[17:43:15] Process dev's dependency serial array [".remove-log-files",".development-env",".mk-dist-dir"]
[17:43:15] -Execute electrode/.remove-log-files as function
[17:43:15] >Done Execute electrode/.remove-log-files as function (1 ms)
[17:43:15] .Execute electrode/.development-env as function
[17:43:15] >Done Execute electrode/.development-env as function (0 ms)
[17:43:15] -Execute electrode/.mk-dist-dir as function
[17:43:15] >Done Execute electrode/.mk-dist-dir as function (1 ms)
[17:43:15] Done Process dev's dependency serial array [".remove-log-files",".development-env",".mk-dist-dir"] (6 ms)
[17:43:15] Execute electrode/dev as function
[17:43:15] -Process electrode/dev.fR concurrent array [".webpack-dev",["server-watch ","generate-service-worker"]]
[17:43:15] ..Execute electrode/.webpack-dev as function
[17:43:15] --Process electrode/dev.fR.C concurrent array ["server-watch ","generate-service-worker"]
[17:43:15] >>Done Execute electrode/.webpack-dev as function (16 ms)
[17:43:15] ...Execute electrode/generate-service-worker as function
[17:43:15] ---Process server-watch's dependency serial array [".init-bundle.valid.log"]
[17:43:15] >>>Done Execute electrode/generate-service-worker as function (18 ms)
[17:43:15] ....Execute electrode/.init-bundle.valid.log as function
[17:43:15] >>>>Done Execute electrode/.init-bundle.valid.log as function (3 ms)
[17:43:15] >>>Done Process server-watch's dependency serial array [".init-bundle.valid.log"] (25 ms)
[17:43:15] ---Execute electrode/server-watch as function
[17:43:15] ....Execute nodemon   --delay 1 --ext js,jsx,json,yaml,log --watch config --exec node "CWD/~/electrode-archetype-react-app/support/babel-run" src/server
[nodemon] 1.17.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: /Sites/test/electrode-4/config/**/*
[nodemon] starting `node /Sites/test/electrode-4/node_modules/electrode-archetype-react-app/support/babel-run src/server`
TypeError: router is not a function
    at _.each.method (/Users/siarhei206492423/Sites/test/electrode-4/node_modules/electrode-react-webapp/lib/koa/index.js:70:7)
    at arrayEach (/Users/siarhei206492423/Sites/test/electrode-4/node_modules/lodash/lodash.js:516:11)
    at Function.forEach (/Users/siarhei206492423/Sites/test/electrode-4/node_modules/lodash/lodash.js:9342:14)
    at _.each (/Users/siarhei206492423/Sites/test/electrode-4/node_modules/electrode-react-webapp/lib/koa/index.js:64:7)
    at /Sites/test/electrode-4/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/Sites/test/electrode-4/node_modules/lodash/lodash.js:3010:24)
    at /Sites/test/electrode-4/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/Sites/test/electrode-4/node_modules/lodash/lodash.js:9342:14)
    at registerRoutes (/Sites/test/electrode-4/node_modules/electrode-react-webapp/lib/koa/index.js:42:5)
    at Promise (/Sites/test/electrode-4/src/server/koa-server.js:37:12)
    at setRouteHandler (/Sites/test/electrode-4/src/server/koa-server.js:34:3)
From previous event:
    at electrodeServer (/Sites/test/electrode-4/src/server/koa-server.js:64:6)
    at startServer (/Sites/test/electrode-4/src/server/index.js:16:10)
    at support.load.then (/Sites/test/electrode-4/src/server/index.js:23:12)
    at <anonymous>
[nodemon] clean exit - waiting for changes before restart
```

**Comment by jchip** [comment]
Hi, thanks for reporting the issue.

We haven't had time to update express and koa support for the new React Router 4 yet.  It's in our pipeline.

**Comment by sergesemashko** [comment]
Got it, thanks. Out of curiosity, Is there a way to expose what is being worked on from the pipeline? We are using koa on the project and currently locked to the previous version, but would like to upgrade. So, I would consider contributing for koa support to facilitate the upgrade.

**Comment by jchip** [comment]
We are required to use our internal Jira to track our work.  We don't use Koa internally so it's basically when we catch a break then we do it.  If you can make Koa work and upgrade to the latest Koa, then that'd be awesome.
