### ISSUE TITLE
Methods prop in route definition not being respected

### ISSUE THREAD

**Issue by clopes-ventureoak** [electrode-io/electrode#912]
## Type of issue

Bug in electrode-redux-router-engine
This started to happen after upgrade from 1.5.3 to 2.1.4

## My environment

* *OS version/details*: Ubuntu 18.04 64bits
* *Node version:* 8.9.1
* *npm version:* 6.1.0

## Expected behavior

According to the documentation https://docs.electrode.io/other/stand-alone-modules/redux-router-engine#define-your-routes defining a `methods` prop should allow to change the HTTP methods the route allows on the server.

## Current behavior

Adding `methods` with `head` does not change behaviour, it returns an 500 error.

## Steps to reproduce the behavior

Add `methods` to top route, make a head request.

## Command line output

```
electrode-redux-router-engine Error: Error: electrode-redux-router-engine: /paht-with-head-in-methods doesn't allow request method head
    at ReduxRouterEngine.checkMatch (/node_modules/electrode-redux-router-engine/lib/redux-router-engine.js:93:13)
    at ReduxRouterEngine.render (/node_modules/electrode-redux-router-engine/lib/redux-router-engine.js:104:29)
    at Context.it (/node_modules/electrode-redux-router-engine/test/spec/redux-router-engine.spec.js:308:19)
    at callFn (/node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runnable.js:348:21)
    at Test.Runnable.run (/node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runnable.js:340:7)
    at Runner.runTest (/node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runner.js:443:10)
    at /node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runner.js:549:12
    at next (/node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runner.js:361:14)
    at /node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runner.js:371:7
    at next (/node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runner.js:295:14)
    at /node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runner.js:334:7
    at done (/node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runnable.js:295:5)
    at callFn (/node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runnable.js:366:7)
    at Hook.Runnable.run (/node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runnable.js:340:7)
    at next (/node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runner.js:309:10)
    at Immediate.<anonymous> (/node_modules/electrode-redux-router-engine/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
## Extra investigation
Debugging the problem I found out that the `match[0]` at `checkMatch` has an object route, and is the route that as `methods`prop. If I change the methods assignment to `const methods = match[0].route.methods || "get";` everything works.
Also, in the tests there is a test `should return 500 for method not allowed` that checks that the route `/post-only` is returning 500. I couldn't quite understand this test, because the route is `post-only` but then the test is expecting a 500 and also the route definition has a prop `method` with `post`, but there is no `method` prop in the documentation, only `methods`. With my change and removing the `method` prop the tests still passes (I also change the route to `not-post` just to make it more clear.
Maybe a test `should return 200 for allowed method` would also make sense.

**Comment by jchip** [comment]
Thanks for filing the issue with details from the excellent investigative work.  You are right about the cause of the issue and the problem with the tests.  Since you already did this part, is it OK if I request a PR from you to fix it and add the test you suggested?  Thanks.

**Comment by clopes-ventureoak** [comment]
Sure, it is done.
